/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.firecrawl.agent.model


case class WorkerProgress(
  id: Option[String] = None,
  status: Option[WorkerProgressEnums.Status] = None,
  steps: Option[Int] = None,
  currentTool: Option[String] = None,
  tokens: Option[Int] = None,
  stepLog: Option[Seq[WorkerProgressStepLogInner]] = None
)

object WorkerProgressEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Running = Value("running")
    val Done = Value("done")
    val Error = Value("error")
  }

}
