/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.firecrawl.agent.models

import com.firecrawl.agent.models.ModelConfig
import com.firecrawl.agent.models.SubAgentConfig

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param prompt The research task or question.
 * @param stream If true, response is an SSE stream of AgentEvent objects.
 * @param format Desired output format. If set, agent will format data accordingly.
 * @param schema JSON schema that serves as both a research plan and output format. The agent treats each field as a data point to collect during research. Array fields mean \"find all items.\" The final output is compiled into this exact shape. Used with format=json. 
 * @param columns Column names for CSV output. Each column acts as a required data point the agent will research. The final CSV contains one column per entry. 
 * @param urls Seed URLs to start from instead of searching.
 * @param model 
 * @param subAgentModel 
 * @param maxSteps Maximum agent steps before stopping.
 * @param skills Skills to pre-load for this run.
 * @param skillInstructions Per-skill custom instructions. Keys are skill names, values are instruction strings appended when the skill is loaded. 
 * @param subAgents Sub-agents available during this run. Each sub-agent becomes a tool the orchestrator can delegate tasks to. 
 * @param exportSkill When true, post-processes the run into a reusable skill package (SKILL.md + workflow.mjs + schema.json) returned in the response. 
 */


data class RunRequest (

    /* The research task or question. */
    @Json(name = "prompt")
    val prompt: kotlin.String,

    /* If true, response is an SSE stream of AgentEvent objects. */
    @Json(name = "stream")
    val stream: kotlin.Boolean? = false,

    /* Desired output format. If set, agent will format data accordingly. */
    @Json(name = "format")
    val format: RunRequest.Format? = null,

    /* JSON schema that serves as both a research plan and output format. The agent treats each field as a data point to collect during research. Array fields mean \"find all items.\" The final output is compiled into this exact shape. Used with format=json.  */
    @Json(name = "schema")
    val schema: kotlin.Any? = null,

    /* Column names for CSV output. Each column acts as a required data point the agent will research. The final CSV contains one column per entry.  */
    @Json(name = "columns")
    val columns: kotlin.collections.List<kotlin.String>? = null,

    /* Seed URLs to start from instead of searching. */
    @Json(name = "urls")
    val urls: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "model")
    val model: ModelConfig? = null,

    @Json(name = "subAgentModel")
    val subAgentModel: ModelConfig? = null,

    /* Maximum agent steps before stopping. */
    @Json(name = "maxSteps")
    val maxSteps: kotlin.Int? = 15,

    /* Skills to pre-load for this run. */
    @Json(name = "skills")
    val skills: kotlin.collections.List<kotlin.String>? = null,

    /* Per-skill custom instructions. Keys are skill names, values are instruction strings appended when the skill is loaded.  */
    @Json(name = "skillInstructions")
    val skillInstructions: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Sub-agents available during this run. Each sub-agent becomes a tool the orchestrator can delegate tasks to.  */
    @Json(name = "subAgents")
    val subAgents: kotlin.collections.List<SubAgentConfig>? = null,

    /* When true, post-processes the run into a reusable skill package (SKILL.md + workflow.mjs + schema.json) returned in the response.  */
    @Json(name = "exportSkill")
    val exportSkill: kotlin.Boolean? = false

) {

    /**
     * Desired output format. If set, agent will format data accordingly.
     *
     * Values: json,csv,markdown
     */
    @JsonClass(generateAdapter = false)
    enum class Format(val value: kotlin.String) {
        @Json(name = "json") json("json"),
        @Json(name = "csv") csv("csv"),
        @Json(name = "markdown") markdown("markdown");
    }

}

