// <auto-generated>
/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using FirecrawlAgent.Client;

namespace FirecrawlAgent.Model
{
    /// <summary>
    /// AgentEventOneOf5
    /// </summary>
    public partial class AgentEventOneOf5 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentEventOneOf5" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="error">error</param>
        [JsonConstructor]
        public AgentEventOneOf5(Option<Object?> type = default, Option<string?> error = default)
        {
            TypeOption = type;
            ErrorOption = error;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public Object? Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Error
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ErrorOption { get; private set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [JsonPropertyName("error")]
        public string? Error { get { return this.ErrorOption; } set { this.ErrorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentEventOneOf5 {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AgentEventOneOf5" />
    /// </summary>
    public class AgentEventOneOf5JsonConverter : JsonConverter<AgentEventOneOf5>
    {
        /// <summary>
        /// Deserializes json to <see cref="AgentEventOneOf5" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AgentEventOneOf5 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Object?> type = default;
            Option<string?> error = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "error":
                            error = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (error.IsSet && error.Value == null)
                throw new ArgumentNullException(nameof(error), "Property is not nullable for class AgentEventOneOf5.");

            return new AgentEventOneOf5(type, error);
        }

        /// <summary>
        /// Serializes a <see cref="AgentEventOneOf5" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentEventOneOf5"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AgentEventOneOf5 agentEventOneOf5, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, agentEventOneOf5, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AgentEventOneOf5" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentEventOneOf5"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AgentEventOneOf5 agentEventOneOf5, JsonSerializerOptions jsonSerializerOptions)
        {
            if (agentEventOneOf5.ErrorOption.IsSet && agentEventOneOf5.Error == null)
                throw new ArgumentNullException(nameof(agentEventOneOf5.Error), "Property is required for class AgentEventOneOf5.");

            if (agentEventOneOf5.TypeOption.IsSet)
                if (agentEventOneOf5.TypeOption.Value != null)
                {
                    writer.WritePropertyName("type");
                    JsonSerializer.Serialize(writer, agentEventOneOf5.Type, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("type");
            if (agentEventOneOf5.ErrorOption.IsSet)
                writer.WriteString("error", agentEventOneOf5.Error);
        }
    }
}
