// <auto-generated>
/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using FirecrawlAgent.Client;

namespace FirecrawlAgent.Model
{
    /// <summary>
    /// WorkerProgress
    /// </summary>
    public partial class WorkerProgress : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WorkerProgress" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="status">status</param>
        /// <param name="steps">steps</param>
        /// <param name="currentTool">currentTool</param>
        /// <param name="tokens">tokens</param>
        /// <param name="stepLog">stepLog</param>
        [JsonConstructor]
        public WorkerProgress(Option<string?> id = default, Option<StatusEnum?> status = default, Option<int?> steps = default, Option<string?> currentTool = default, Option<int?> tokens = default, Option<List<WorkerProgressStepLogInner>?> stepLog = default)
        {
            IdOption = id;
            StatusOption = status;
            StepsOption = steps;
            CurrentToolOption = currentTool;
            TokensOption = tokens;
            StepLogOption = stepLog;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Defines Status
        /// </summary>
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Running for value: running
            /// </summary>
            Running = 1,

            /// <summary>
            /// Enum Done for value: done
            /// </summary>
            Done = 2,

            /// <summary>
            /// Enum Error for value: error
            /// </summary>
            Error = 3
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static StatusEnum StatusEnumFromString(string value)
        {
            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("done"))
                return StatusEnum.Done;

            if (value.Equals("error"))
                return StatusEnum.Error;

            throw new NotImplementedException($"Could not convert value to type StatusEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="StatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static StatusEnum? StatusEnumFromStringOrDefault(string value)
        {
            if (value.Equals("running"))
                return StatusEnum.Running;

            if (value.Equals("done"))
                return StatusEnum.Done;

            if (value.Equals("error"))
                return StatusEnum.Error;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="StatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string StatusEnumToJsonValue(StatusEnum? value)
        {
            if (value == StatusEnum.Running)
                return "running";

            if (value == StatusEnum.Done)
                return "done";

            if (value == StatusEnum.Error)
                return "error";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<StatusEnum?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public StatusEnum? Status { get { return this.StatusOption.Value; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Steps
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> StepsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Steps
        /// </summary>
        [JsonPropertyName("steps")]
        public int? Steps { get { return this.StepsOption; } set { this.StepsOption = new(value); } }

        /// <summary>
        /// Used to track the state of CurrentTool
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> CurrentToolOption { get; private set; }

        /// <summary>
        /// Gets or Sets CurrentTool
        /// </summary>
        [JsonPropertyName("currentTool")]
        public string? CurrentTool { get { return this.CurrentToolOption; } set { this.CurrentToolOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tokens
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TokensOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tokens
        /// </summary>
        [JsonPropertyName("tokens")]
        public int? Tokens { get { return this.TokensOption; } set { this.TokensOption = new(value); } }

        /// <summary>
        /// Used to track the state of StepLog
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<WorkerProgressStepLogInner>?> StepLogOption { get; private set; }

        /// <summary>
        /// Gets or Sets StepLog
        /// </summary>
        [JsonPropertyName("stepLog")]
        public List<WorkerProgressStepLogInner>? StepLog { get { return this.StepLogOption; } set { this.StepLogOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkerProgress {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Steps: ").Append(Steps).Append("\n");
            sb.Append("  CurrentTool: ").Append(CurrentTool).Append("\n");
            sb.Append("  Tokens: ").Append(Tokens).Append("\n");
            sb.Append("  StepLog: ").Append(StepLog).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="WorkerProgress" />
    /// </summary>
    public class WorkerProgressJsonConverter : JsonConverter<WorkerProgress>
    {
        /// <summary>
        /// Deserializes json to <see cref="WorkerProgress" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override WorkerProgress Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> id = default;
            Option<WorkerProgress.StatusEnum?> status = default;
            Option<int?> steps = default;
            Option<string?> currentTool = default;
            Option<int?> tokens = default;
            Option<List<WorkerProgressStepLogInner>?> stepLog = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<WorkerProgress.StatusEnum?>(WorkerProgress.StatusEnumFromStringOrDefault(statusRawValue));
                            break;
                        case "steps":
                            steps = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "currentTool":
                            currentTool = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tokens":
                            tokens = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "stepLog":
                            stepLog = new Option<List<WorkerProgressStepLogInner>?>(JsonSerializer.Deserialize<List<WorkerProgressStepLogInner>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class WorkerProgress.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class WorkerProgress.");

            if (steps.IsSet && steps.Value == null)
                throw new ArgumentNullException(nameof(steps), "Property is not nullable for class WorkerProgress.");

            if (currentTool.IsSet && currentTool.Value == null)
                throw new ArgumentNullException(nameof(currentTool), "Property is not nullable for class WorkerProgress.");

            if (tokens.IsSet && tokens.Value == null)
                throw new ArgumentNullException(nameof(tokens), "Property is not nullable for class WorkerProgress.");

            if (stepLog.IsSet && stepLog.Value == null)
                throw new ArgumentNullException(nameof(stepLog), "Property is not nullable for class WorkerProgress.");

            return new WorkerProgress(id, status, steps, currentTool, tokens, stepLog);
        }

        /// <summary>
        /// Serializes a <see cref="WorkerProgress" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerProgress"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, WorkerProgress workerProgress, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, workerProgress, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="WorkerProgress" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="workerProgress"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, WorkerProgress workerProgress, JsonSerializerOptions jsonSerializerOptions)
        {
            if (workerProgress.IdOption.IsSet && workerProgress.Id == null)
                throw new ArgumentNullException(nameof(workerProgress.Id), "Property is required for class WorkerProgress.");

            if (workerProgress.CurrentToolOption.IsSet && workerProgress.CurrentTool == null)
                throw new ArgumentNullException(nameof(workerProgress.CurrentTool), "Property is required for class WorkerProgress.");

            if (workerProgress.StepLogOption.IsSet && workerProgress.StepLog == null)
                throw new ArgumentNullException(nameof(workerProgress.StepLog), "Property is required for class WorkerProgress.");

            if (workerProgress.IdOption.IsSet)
                writer.WriteString("id", workerProgress.Id);

            var statusRawValue = WorkerProgress.StatusEnumToJsonValue(workerProgress.StatusOption.Value!.Value);
            writer.WriteString("status", statusRawValue);
            if (workerProgress.StepsOption.IsSet)
                writer.WriteNumber("steps", workerProgress.StepsOption.Value!.Value);

            if (workerProgress.CurrentToolOption.IsSet)
                writer.WriteString("currentTool", workerProgress.CurrentTool);

            if (workerProgress.TokensOption.IsSet)
                writer.WriteNumber("tokens", workerProgress.TokensOption.Value!.Value);

            if (workerProgress.StepLogOption.IsSet)
            {
                writer.WritePropertyName("stepLog");
                JsonSerializer.Serialize(writer, workerProgress.StepLog, jsonSerializerOptions);
            }
        }
    }
}
