/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FirecrawlAgent/model/AgentEvent_oneOf_1.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AgentEvent_oneOf_1::AgentEvent_oneOf_1()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_InputIsSet = false;
}

AgentEvent_oneOf_1::~AgentEvent_oneOf_1()
{
}

void AgentEvent_oneOf_1::validate()
{
    // TODO: implement validation
}

web::json::value AgentEvent_oneOf_1::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Type.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type.get());
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_InputIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("input"))] = ModelBase::toJson(m_Input);
    }

    return val;
}

bool AgentEvent_oneOf_1::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("input"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("input")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setInput;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInput);
            setInput(refVal_setInput);
            
        }
    }
    return ok;
}

void AgentEvent_oneOf_1::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Type.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type.get()));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_InputIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("input")), m_Input));
    }
}

bool AgentEvent_oneOf_1::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        std::shared_ptr<AnyType> refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("input"))))
    {
        std::shared_ptr<Object> refVal_setInput;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("input"))), refVal_setInput );
        setInput(refVal_setInput);
    }
    return ok;
}


std::shared_ptr<AnyType> AgentEvent_oneOf_1::getType() const
{
    return m_Type.get();
}


void AgentEvent_oneOf_1::setType(const std::shared_ptr<AnyType>& value)
{
    m_Type = value;
}

bool AgentEvent_oneOf_1::typeIsSet() const
{
    return m_Type.has_value();
}

void AgentEvent_oneOf_1::unsetType()
{
    m_Type.reset();
}
utility::string_t AgentEvent_oneOf_1::getName() const
{
    return m_Name;
}


void AgentEvent_oneOf_1::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool AgentEvent_oneOf_1::nameIsSet() const
{
    return m_NameIsSet;
}

void AgentEvent_oneOf_1::unsetName()
{
    m_NameIsSet = false;
}
std::shared_ptr<Object> AgentEvent_oneOf_1::getInput() const
{
    return m_Input;
}


void AgentEvent_oneOf_1::setInput(const std::shared_ptr<Object>& value)
{
    m_Input = value;
    m_InputIsSet = true;
}

bool AgentEvent_oneOf_1::inputIsSet() const
{
    return m_InputIsSet;
}

void AgentEvent_oneOf_1::unsetInput()
{
    m_InputIsSet = false;
}

}
}
}
}


