/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FirecrawlAgent/model/AgentEvent_oneOf_4.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

AgentEvent_oneOf_4::AgentEvent_oneOf_4()
{
    m_Text = utility::conversions::to_string_t("");
    m_TextIsSet = false;
    m_StepsIsSet = false;
    m_UsageIsSet = false;
}

AgentEvent_oneOf_4::~AgentEvent_oneOf_4()
{
}

void AgentEvent_oneOf_4::validate()
{
    // TODO: implement validation
}

web::json::value AgentEvent_oneOf_4::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_Type.has_value())
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("type"))] = ModelBase::toJson(m_Type.get());
    }
    if(m_TextIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("text"))] = ModelBase::toJson(m_Text);
    }
    if(m_StepsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("steps"))] = ModelBase::toJson(m_Steps);
    }
    if(m_UsageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("usage"))] = ModelBase::toJson(m_Usage);
    }

    return val;
}

bool AgentEvent_oneOf_4::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("type")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setType;
            ok &= ModelBase::fromJson(fieldValue, refVal_setType);
            setType(refVal_setType);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("text")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setText;
            ok &= ModelBase::fromJson(fieldValue, refVal_setText);
            setText(refVal_setText);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("steps"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("steps")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<StepDetail>> refVal_setSteps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSteps);
            setSteps(refVal_setSteps);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("usage"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("usage")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Usage> refVal_setUsage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUsage);
            setUsage(refVal_setUsage);
            
        }
    }
    return ok;
}

void AgentEvent_oneOf_4::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_Type.has_value())
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("type")), m_Type.get()));
    }
    if(m_TextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("text")), m_Text));
    }
    if(m_StepsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("steps")), m_Steps));
    }
    if(m_UsageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("usage")), m_Usage));
    }
}

bool AgentEvent_oneOf_4::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("type"))))
    {
        std::shared_ptr<AnyType> refVal_setType;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("type"))), refVal_setType );
        setType(refVal_setType);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        utility::string_t refVal_setText;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("text"))), refVal_setText );
        setText(refVal_setText);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("steps"))))
    {
        std::vector<std::shared_ptr<StepDetail>> refVal_setSteps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("steps"))), refVal_setSteps );
        setSteps(refVal_setSteps);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("usage"))))
    {
        std::shared_ptr<Usage> refVal_setUsage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("usage"))), refVal_setUsage );
        setUsage(refVal_setUsage);
    }
    return ok;
}


std::shared_ptr<AnyType> AgentEvent_oneOf_4::getType() const
{
    return m_Type.get();
}


void AgentEvent_oneOf_4::setType(const std::shared_ptr<AnyType>& value)
{
    m_Type = value;
}

bool AgentEvent_oneOf_4::typeIsSet() const
{
    return m_Type.has_value();
}

void AgentEvent_oneOf_4::unsetType()
{
    m_Type.reset();
}
utility::string_t AgentEvent_oneOf_4::getText() const
{
    return m_Text;
}


void AgentEvent_oneOf_4::setText(const utility::string_t& value)
{
    m_Text = value;
    m_TextIsSet = true;
}

bool AgentEvent_oneOf_4::textIsSet() const
{
    return m_TextIsSet;
}

void AgentEvent_oneOf_4::unsetText()
{
    m_TextIsSet = false;
}
std::vector<std::shared_ptr<StepDetail>> AgentEvent_oneOf_4::getSteps() const
{
    return m_Steps;
}


void AgentEvent_oneOf_4::setSteps(const std::vector<std::shared_ptr<StepDetail>>& value)
{
    m_Steps = value;
    m_StepsIsSet = true;
}

bool AgentEvent_oneOf_4::stepsIsSet() const
{
    return m_StepsIsSet;
}

void AgentEvent_oneOf_4::unsetSteps()
{
    m_StepsIsSet = false;
}
std::shared_ptr<Usage> AgentEvent_oneOf_4::getUsage() const
{
    return m_Usage;
}


void AgentEvent_oneOf_4::setUsage(const std::shared_ptr<Usage>& value)
{
    m_Usage = value;
    m_UsageIsSet = true;
}

bool AgentEvent_oneOf_4::usageIsSet() const
{
    return m_UsageIsSet;
}

void AgentEvent_oneOf_4::unsetUsage()
{
    m_UsageIsSet = false;
}

}
}
}
}


