/*
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firecrawl.agent.api;

import com.firecrawl.agent.ApiException;
import com.firecrawl.agent.model.ErrorResponse;
import com.firecrawl.agent.model.RunRequest;
import com.firecrawl.agent.model.RunResponse;
import com.firecrawl.agent.model.Skill;
import com.firecrawl.agent.model.WorkerProgress;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Get parallel worker progress
     *
     * Poll for progress of currently running parallel workers.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getWorkerProgressTest() throws ApiException {
        Map<String, WorkerProgress> response = api.getWorkerProgress();
        // TODO: test validations
    }

    /**
     * List available skills
     *
     * Returns all discovered skills the agent can use.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listSkillsTest() throws ApiException {
        List<Skill> response = api.listSkills();
        // TODO: test validations
    }

    /**
     * Run the agent
     *
     * Execute a web research task. Supports both streaming (SSE) and non-streaming responses. This is the single consolidated endpoint that replaces /query, /extract, and /plan. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void runTest() throws ApiException {
        RunRequest runRequest = null;
        RunResponse response = api.run(runRequest);
        // TODO: test validations
    }

}
