/*
Firecrawl Agent API

AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firecrawlagent

import (
	"encoding/json"
)

// checks if the AgentEventOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentEventOneOf4{}

// AgentEventOneOf4 struct for AgentEventOneOf4
type AgentEventOneOf4 struct {
	Type interface{} `json:"type,omitempty"`
	Text *string `json:"text,omitempty"`
	Steps []StepDetail `json:"steps,omitempty"`
	Usage *Usage `json:"usage,omitempty"`
}

// NewAgentEventOneOf4 instantiates a new AgentEventOneOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentEventOneOf4() *AgentEventOneOf4 {
	this := AgentEventOneOf4{}
	return &this
}

// NewAgentEventOneOf4WithDefaults instantiates a new AgentEventOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentEventOneOf4WithDefaults() *AgentEventOneOf4 {
	this := AgentEventOneOf4{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentEventOneOf4) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentEventOneOf4) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AgentEventOneOf4) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given interface{} and assigns it to the Type field.
func (o *AgentEventOneOf4) SetType(v interface{}) {
	o.Type = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *AgentEventOneOf4) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentEventOneOf4) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *AgentEventOneOf4) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *AgentEventOneOf4) SetText(v string) {
	o.Text = &v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *AgentEventOneOf4) GetSteps() []StepDetail {
	if o == nil || IsNil(o.Steps) {
		var ret []StepDetail
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentEventOneOf4) GetStepsOk() ([]StepDetail, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *AgentEventOneOf4) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []StepDetail and assigns it to the Steps field.
func (o *AgentEventOneOf4) SetSteps(v []StepDetail) {
	o.Steps = v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *AgentEventOneOf4) GetUsage() Usage {
	if o == nil || IsNil(o.Usage) {
		var ret Usage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentEventOneOf4) GetUsageOk() (*Usage, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *AgentEventOneOf4) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given Usage and assigns it to the Usage field.
func (o *AgentEventOneOf4) SetUsage(v Usage) {
	o.Usage = &v
}

func (o AgentEventOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentEventOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableAgentEventOneOf4 struct {
	value *AgentEventOneOf4
	isSet bool
}

func (v NullableAgentEventOneOf4) Get() *AgentEventOneOf4 {
	return v.value
}

func (v *NullableAgentEventOneOf4) Set(val *AgentEventOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentEventOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentEventOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentEventOneOf4(val *AgentEventOneOf4) *NullableAgentEventOneOf4 {
	return &NullableAgentEventOneOf4{value: val, isSet: true}
}

func (v NullableAgentEventOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentEventOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


