#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Text
No description available.
.PARAMETER ToolCalls
No description available.
.PARAMETER ToolResults
No description available.
.OUTPUTS

StepDetail<PSCustomObject>
#>

function Initialize-StepDetail {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Text},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ToolCalls},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ToolResults}
    )

    Process {
        'Creating PSCustomObject: FirecrawlAgent => StepDetail' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "text" = ${Text}
            "toolCalls" = ${ToolCalls}
            "toolResults" = ${ToolResults}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to StepDetail<PSCustomObject>

.DESCRIPTION

Convert from JSON to StepDetail<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

StepDetail<PSCustomObject>
#>
function ConvertFrom-JsonToStepDetail {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FirecrawlAgent => StepDetail' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in StepDetail
        $AllProperties = ("text", "toolCalls", "toolResults")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "text"))) { #optional property not found
            $Text = $null
        } else {
            $Text = $JsonParameters.PSobject.Properties["text"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "toolCalls"))) { #optional property not found
            $ToolCalls = $null
        } else {
            $ToolCalls = $JsonParameters.PSobject.Properties["toolCalls"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "toolResults"))) { #optional property not found
            $ToolResults = $null
        } else {
            $ToolResults = $JsonParameters.PSobject.Properties["toolResults"].value
        }

        $PSO = [PSCustomObject]@{
            "text" = ${Text}
            "toolCalls" = ${ToolCalls}
            "toolResults" = ${ToolResults}
        }

        return $PSO
    }

}

