/*
Firecrawl Agent API

AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firecrawlagent

import (
	"encoding/json"
)

// checks if the AgentEventOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentEventOneOf2{}

// AgentEventOneOf2 struct for AgentEventOneOf2
type AgentEventOneOf2 struct {
	Type interface{} `json:"type,omitempty"`
	Name *string `json:"name,omitempty"`
	Output map[string]interface{} `json:"output,omitempty"`
}

// NewAgentEventOneOf2 instantiates a new AgentEventOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentEventOneOf2() *AgentEventOneOf2 {
	this := AgentEventOneOf2{}
	return &this
}

// NewAgentEventOneOf2WithDefaults instantiates a new AgentEventOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentEventOneOf2WithDefaults() *AgentEventOneOf2 {
	this := AgentEventOneOf2{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentEventOneOf2) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentEventOneOf2) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AgentEventOneOf2) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given interface{} and assigns it to the Type field.
func (o *AgentEventOneOf2) SetType(v interface{}) {
	o.Type = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentEventOneOf2) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentEventOneOf2) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentEventOneOf2) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentEventOneOf2) SetName(v string) {
	o.Name = &v
}

// GetOutput returns the Output field value if set, zero value otherwise.
func (o *AgentEventOneOf2) GetOutput() map[string]interface{} {
	if o == nil || IsNil(o.Output) {
		var ret map[string]interface{}
		return ret
	}
	return o.Output
}

// GetOutputOk returns a tuple with the Output field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentEventOneOf2) GetOutputOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Output) {
		return map[string]interface{}{}, false
	}
	return o.Output, true
}

// HasOutput returns a boolean if a field has been set.
func (o *AgentEventOneOf2) HasOutput() bool {
	if o != nil && !IsNil(o.Output) {
		return true
	}

	return false
}

// SetOutput gets a reference to the given map[string]interface{} and assigns it to the Output field.
func (o *AgentEventOneOf2) SetOutput(v map[string]interface{}) {
	o.Output = v
}

func (o AgentEventOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentEventOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Output) {
		toSerialize["output"] = o.Output
	}
	return toSerialize, nil
}

type NullableAgentEventOneOf2 struct {
	value *AgentEventOneOf2
	isSet bool
}

func (v NullableAgentEventOneOf2) Get() *AgentEventOneOf2 {
	return v.value
}

func (v *NullableAgentEventOneOf2) Set(val *AgentEventOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentEventOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentEventOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentEventOneOf2(val *AgentEventOneOf2) *NullableAgentEventOneOf2 {
	return &NullableAgentEventOneOf2{value: val, isSet: true}
}

func (v NullableAgentEventOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentEventOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


