=begin
#Firecrawl Agent API

#AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'firecrawl_agent/api_client'
require 'firecrawl_agent/api_error'
require 'firecrawl_agent/api_model_base'
require 'firecrawl_agent/version'
require 'firecrawl_agent/configuration'

# Models
require 'firecrawl_agent/models/agent_event'
require 'firecrawl_agent/models/agent_event_one_of'
require 'firecrawl_agent/models/agent_event_one_of1'
require 'firecrawl_agent/models/agent_event_one_of2'
require 'firecrawl_agent/models/agent_event_one_of3'
require 'firecrawl_agent/models/agent_event_one_of4'
require 'firecrawl_agent/models/agent_event_one_of5'
require 'firecrawl_agent/models/error_response'
require 'firecrawl_agent/models/exported_skill'
require 'firecrawl_agent/models/model_config'
require 'firecrawl_agent/models/run_request'
require 'firecrawl_agent/models/run_response'
require 'firecrawl_agent/models/skill'
require 'firecrawl_agent/models/step_detail'
require 'firecrawl_agent/models/step_detail_tool_calls_inner'
require 'firecrawl_agent/models/step_detail_tool_results_inner'
require 'firecrawl_agent/models/sub_agent_config'
require 'firecrawl_agent/models/usage'
require 'firecrawl_agent/models/worker_progress'
require 'firecrawl_agent/models/worker_progress_step_log_inner'

# APIs
require 'firecrawl_agent/api/default_api'

module FirecrawlAgent
  class << self
    # Customize default settings for the SDK using block.
    #   FirecrawlAgent.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
