# NOTE: This file is auto generated by OpenAPI Generator 7.21.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FirecrawlAgentAPI.Model.AgentEventOneOf2 do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :name,
    :output
  ]

  @type t :: %__MODULE__{
    :type => any() | nil,
    :name => String.t | nil,
    :output => map() | nil
  }

  def decode(value) do
    value
  end
end

