# NOTE: This file is auto generated by OpenAPI Generator 7.21.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FirecrawlAgentAPI.Model.WorkerProgress do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :status,
    :steps,
    :currentTool,
    :tokens,
    :stepLog
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :status => String.t | nil,
    :steps => integer() | nil,
    :currentTool => String.t | nil,
    :tokens => integer() | nil,
    :stepLog => [FirecrawlAgentAPI.Model.WorkerProgressStepLogInner.t] | nil
  }

  alias FirecrawlAgentAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:stepLog, :list, FirecrawlAgentAPI.Model.WorkerProgressStepLogInner)
  end
end

