/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FirecrawlAgent/model/RunRequest.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RunRequest::RunRequest()
{
    m_Prompt = utility::conversions::to_string_t("");
    m_PromptIsSet = false;
    m_Stream = false;
    m_StreamIsSet = false;
    m_FormatIsSet = false;
    m_SchemaIsSet = false;
    m_ColumnsIsSet = false;
    m_UrlsIsSet = false;
    m_ModelIsSet = false;
    m_SubAgentModelIsSet = false;
    m_MaxSteps = 0;
    m_MaxStepsIsSet = false;
    m_SkillsIsSet = false;
}

RunRequest::~RunRequest()
{
}

void RunRequest::validate()
{
    // TODO: implement validation
}

web::json::value RunRequest::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_PromptIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("prompt"))] = ModelBase::toJson(m_Prompt);
    }
    if(m_StreamIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("stream"))] = ModelBase::toJson(m_Stream);
    }
    if(m_FormatIsSet)
    {
        
        utility::string_t refVal = fromFormatEnum(m_Format);
        val[utility::conversions::to_string_t(_XPLATSTR("format"))] = ModelBase::toJson(refVal);
        
    }
    if(m_SchemaIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("schema"))] = ModelBase::toJson(m_Schema);
    }
    if(m_ColumnsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("columns"))] = ModelBase::toJson(m_Columns);
    }
    if(m_UrlsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("urls"))] = ModelBase::toJson(m_Urls);
    }
    if(m_ModelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("model"))] = ModelBase::toJson(m_Model);
    }
    if(m_SubAgentModelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("subAgentModel"))] = ModelBase::toJson(m_SubAgentModel);
    }
    if(m_MaxStepsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("maxSteps"))] = ModelBase::toJson(m_MaxSteps);
    }
    if(m_SkillsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("skills"))] = ModelBase::toJson(m_Skills);
    }

    return val;
}

bool RunRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("prompt"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("prompt")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPrompt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPrompt);
            setPrompt(refVal_setPrompt);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("stream"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("stream")));
        if(!fieldValue.is_null())
        {
            bool refVal_setStream;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStream);
            setStream(refVal_setStream);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("format"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("format")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFormat;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFormat);
            
            setFormat(toFormatEnum(refVal_setFormat));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("schema"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("schema")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Object> refVal_setSchema;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSchema);
            setSchema(refVal_setSchema);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("columns"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("columns")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setColumns;
            ok &= ModelBase::fromJson(fieldValue, refVal_setColumns);
            setColumns(refVal_setColumns);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("urls"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("urls")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setUrls;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrls);
            setUrls(refVal_setUrls);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("model"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("model")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ModelConfig> refVal_setModel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModel);
            setModel(refVal_setModel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("subAgentModel"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("subAgentModel")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ModelConfig> refVal_setSubAgentModel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubAgentModel);
            setSubAgentModel(refVal_setSubAgentModel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("maxSteps"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("maxSteps")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMaxSteps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxSteps);
            setMaxSteps(refVal_setMaxSteps);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("skills"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("skills")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setSkills;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSkills);
            setSkills(refVal_setSkills);
            
        }
    }
    return ok;
}

void RunRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_PromptIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("prompt")), m_Prompt));
    }
    if(m_StreamIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("stream")), m_Stream));
    }
    if(m_FormatIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("format")), fromFormatEnum(m_Format)));
    }
    if(m_SchemaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("schema")), m_Schema));
    }
    if(m_ColumnsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("columns")), m_Columns));
    }
    if(m_UrlsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("urls")), m_Urls));
    }
    if(m_ModelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("model")), m_Model));
    }
    if(m_SubAgentModelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("subAgentModel")), m_SubAgentModel));
    }
    if(m_MaxStepsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("maxSteps")), m_MaxSteps));
    }
    if(m_SkillsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("skills")), m_Skills));
    }
}

bool RunRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("prompt"))))
    {
        utility::string_t refVal_setPrompt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("prompt"))), refVal_setPrompt );
        setPrompt(refVal_setPrompt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("stream"))))
    {
        bool refVal_setStream;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("stream"))), refVal_setStream );
        setStream(refVal_setStream);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("format"))))
    {
        utility::string_t refVal_setFormat;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("format"))), refVal_setFormat );
        setFormat(toFormatEnum(refVal_setFormat));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("schema"))))
    {
        std::shared_ptr<Object> refVal_setSchema;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("schema"))), refVal_setSchema );
        setSchema(refVal_setSchema);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("columns"))))
    {
        std::vector<utility::string_t> refVal_setColumns;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("columns"))), refVal_setColumns );
        setColumns(refVal_setColumns);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("urls"))))
    {
        std::vector<utility::string_t> refVal_setUrls;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("urls"))), refVal_setUrls );
        setUrls(refVal_setUrls);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("model"))))
    {
        std::shared_ptr<ModelConfig> refVal_setModel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("model"))), refVal_setModel );
        setModel(refVal_setModel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("subAgentModel"))))
    {
        std::shared_ptr<ModelConfig> refVal_setSubAgentModel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("subAgentModel"))), refVal_setSubAgentModel );
        setSubAgentModel(refVal_setSubAgentModel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("maxSteps"))))
    {
        int32_t refVal_setMaxSteps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("maxSteps"))), refVal_setMaxSteps );
        setMaxSteps(refVal_setMaxSteps);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("skills"))))
    {
        std::vector<utility::string_t> refVal_setSkills;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("skills"))), refVal_setSkills );
        setSkills(refVal_setSkills);
    }
    return ok;
}

RunRequest::FormatEnum RunRequest::toFormatEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("json")) {
        return FormatEnum::JSON;
    }
    
    if (value == utility::conversions::to_string_t("csv")) {
        return FormatEnum::CSV;
    }
    
    if (value == utility::conversions::to_string_t("markdown")) {
        return FormatEnum::MARKDOWN;
    }
    
    throw std::invalid_argument("Invalid value for conversion to FormatEnum");
}


const utility::string_t RunRequest::fromFormatEnum(const FormatEnum value) const
{
    switch(value)
    {
        
        case FormatEnum::JSON: return utility::conversions::to_string_t("json");
        
        case FormatEnum::CSV: return utility::conversions::to_string_t("csv");
        
        case FormatEnum::MARKDOWN: return utility::conversions::to_string_t("markdown");
        
    }
}


utility::string_t RunRequest::getPrompt() const
{
    return m_Prompt;
}


void RunRequest::setPrompt(const utility::string_t& value)
{
    m_Prompt = value;
    m_PromptIsSet = true;
}

bool RunRequest::promptIsSet() const
{
    return m_PromptIsSet;
}

void RunRequest::unsetPrompt()
{
    m_PromptIsSet = false;
}
bool RunRequest::isStream() const
{
    return m_Stream;
}

void RunRequest::setStream(bool value)
{
    m_Stream = value;
    m_StreamIsSet = true;
}

bool RunRequest::streamIsSet() const
{
    return m_StreamIsSet;
}

void RunRequest::unsetStream()
{
    m_StreamIsSet = false;
}
RunRequest::FormatEnum RunRequest::getFormat() const
{
    return m_Format;
}


void RunRequest::setFormat(const FormatEnum value)
{
    m_Format = value;
    m_FormatIsSet = true;
}

bool RunRequest::formatIsSet() const
{
    return m_FormatIsSet;
}

void RunRequest::unsetFormat()
{
    m_FormatIsSet = false;
}
std::shared_ptr<Object> RunRequest::getSchema() const
{
    return m_Schema;
}


void RunRequest::setSchema(const std::shared_ptr<Object>& value)
{
    m_Schema = value;
    m_SchemaIsSet = true;
}

bool RunRequest::schemaIsSet() const
{
    return m_SchemaIsSet;
}

void RunRequest::unsetSchema()
{
    m_SchemaIsSet = false;
}
std::vector<utility::string_t> RunRequest::getColumns() const
{
    return m_Columns;
}


void RunRequest::setColumns(const std::vector<utility::string_t>& value)
{
    m_Columns = value;
    m_ColumnsIsSet = true;
}

bool RunRequest::columnsIsSet() const
{
    return m_ColumnsIsSet;
}

void RunRequest::unsetColumns()
{
    m_ColumnsIsSet = false;
}
std::vector<utility::string_t> RunRequest::getUrls() const
{
    return m_Urls;
}


void RunRequest::setUrls(const std::vector<utility::string_t>& value)
{
    m_Urls = value;
    m_UrlsIsSet = true;
}

bool RunRequest::urlsIsSet() const
{
    return m_UrlsIsSet;
}

void RunRequest::unsetUrls()
{
    m_UrlsIsSet = false;
}
std::shared_ptr<ModelConfig> RunRequest::getModel() const
{
    return m_Model;
}


void RunRequest::setModel(const std::shared_ptr<ModelConfig>& value)
{
    m_Model = value;
    m_ModelIsSet = true;
}

bool RunRequest::modelIsSet() const
{
    return m_ModelIsSet;
}

void RunRequest::unsetModel()
{
    m_ModelIsSet = false;
}
std::shared_ptr<ModelConfig> RunRequest::getSubAgentModel() const
{
    return m_SubAgentModel;
}


void RunRequest::setSubAgentModel(const std::shared_ptr<ModelConfig>& value)
{
    m_SubAgentModel = value;
    m_SubAgentModelIsSet = true;
}

bool RunRequest::subAgentModelIsSet() const
{
    return m_SubAgentModelIsSet;
}

void RunRequest::unsetSubAgentModel()
{
    m_SubAgentModelIsSet = false;
}
int32_t RunRequest::getMaxSteps() const
{
    return m_MaxSteps;
}

void RunRequest::setMaxSteps(int32_t value)
{
    m_MaxSteps = value;
    m_MaxStepsIsSet = true;
}

bool RunRequest::maxStepsIsSet() const
{
    return m_MaxStepsIsSet;
}

void RunRequest::unsetMaxSteps()
{
    m_MaxStepsIsSet = false;
}
std::vector<utility::string_t> RunRequest::getSkills() const
{
    return m_Skills;
}


void RunRequest::setSkills(const std::vector<utility::string_t>& value)
{
    m_Skills = value;
    m_SkillsIsSet = true;
}

bool RunRequest::skillsIsSet() const
{
    return m_SkillsIsSet;
}

void RunRequest::unsetSkills()
{
    m_SkillsIsSet = false;
}

}
}
}
}


