/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FirecrawlAgent/model/RunResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

RunResponse::RunResponse()
{
    m_Text = utility::conversions::to_string_t("");
    m_TextIsSet = false;
    m_Data = utility::conversions::to_string_t("");
    m_DataIsSet = false;
    m_FormatIsSet = false;
    m_StepsIsSet = false;
    m_UsageIsSet = false;
}

RunResponse::~RunResponse()
{
}

void RunResponse::validate()
{
    // TODO: implement validation
}

web::json::value RunResponse::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TextIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("text"))] = ModelBase::toJson(m_Text);
    }
    if(m_DataIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("data"))] = ModelBase::toJson(m_Data);
    }
    if(m_FormatIsSet)
    {
        
        utility::string_t refVal = fromFormatEnum(m_Format);
        val[utility::conversions::to_string_t(_XPLATSTR("format"))] = ModelBase::toJson(refVal);
        
    }
    if(m_StepsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("steps"))] = ModelBase::toJson(m_Steps);
    }
    if(m_UsageIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("usage"))] = ModelBase::toJson(m_Usage);
    }

    return val;
}

bool RunResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("text")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setText;
            ok &= ModelBase::fromJson(fieldValue, refVal_setText);
            setText(refVal_setText);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("data"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("data")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setData;
            ok &= ModelBase::fromJson(fieldValue, refVal_setData);
            setData(refVal_setData);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("format"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("format")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFormat;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFormat);
            
            setFormat(toFormatEnum(refVal_setFormat));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("steps"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("steps")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<StepDetail>> refVal_setSteps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSteps);
            setSteps(refVal_setSteps);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("usage"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("usage")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Usage> refVal_setUsage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUsage);
            setUsage(refVal_setUsage);
            
        }
    }
    return ok;
}

void RunResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("text")), m_Text));
    }
    if(m_DataIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("data")), m_Data));
    }
    if(m_FormatIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("format")), fromFormatEnum(m_Format)));
    }
    if(m_StepsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("steps")), m_Steps));
    }
    if(m_UsageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("usage")), m_Usage));
    }
}

bool RunResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        utility::string_t refVal_setText;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("text"))), refVal_setText );
        setText(refVal_setText);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("data"))))
    {
        utility::string_t refVal_setData;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("data"))), refVal_setData );
        setData(refVal_setData);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("format"))))
    {
        utility::string_t refVal_setFormat;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("format"))), refVal_setFormat );
        setFormat(toFormatEnum(refVal_setFormat));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("steps"))))
    {
        std::vector<std::shared_ptr<StepDetail>> refVal_setSteps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("steps"))), refVal_setSteps );
        setSteps(refVal_setSteps);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("usage"))))
    {
        std::shared_ptr<Usage> refVal_setUsage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("usage"))), refVal_setUsage );
        setUsage(refVal_setUsage);
    }
    return ok;
}

RunResponse::FormatEnum RunResponse::toFormatEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("json")) {
        return FormatEnum::JSON;
    }
    
    if (value == utility::conversions::to_string_t("csv")) {
        return FormatEnum::CSV;
    }
    
    if (value == utility::conversions::to_string_t("markdown")) {
        return FormatEnum::MARKDOWN;
    }
    
    if (value == utility::conversions::to_string_t("text")) {
        return FormatEnum::TEXT;
    }
    
    throw std::invalid_argument("Invalid value for conversion to FormatEnum");
}


const utility::string_t RunResponse::fromFormatEnum(const FormatEnum value) const
{
    switch(value)
    {
        
        case FormatEnum::JSON: return utility::conversions::to_string_t("json");
        
        case FormatEnum::CSV: return utility::conversions::to_string_t("csv");
        
        case FormatEnum::MARKDOWN: return utility::conversions::to_string_t("markdown");
        
        case FormatEnum::TEXT: return utility::conversions::to_string_t("text");
        
    }
}


utility::string_t RunResponse::getText() const
{
    return m_Text;
}


void RunResponse::setText(const utility::string_t& value)
{
    m_Text = value;
    m_TextIsSet = true;
}

bool RunResponse::textIsSet() const
{
    return m_TextIsSet;
}

void RunResponse::unsetText()
{
    m_TextIsSet = false;
}
utility::string_t RunResponse::getData() const
{
    return m_Data;
}


void RunResponse::setData(const utility::string_t& value)
{
    m_Data = value;
    m_DataIsSet = true;
}

bool RunResponse::dataIsSet() const
{
    return m_DataIsSet;
}

void RunResponse::unsetData()
{
    m_DataIsSet = false;
}
RunResponse::FormatEnum RunResponse::getFormat() const
{
    return m_Format;
}


void RunResponse::setFormat(const FormatEnum value)
{
    m_Format = value;
    m_FormatIsSet = true;
}

bool RunResponse::formatIsSet() const
{
    return m_FormatIsSet;
}

void RunResponse::unsetFormat()
{
    m_FormatIsSet = false;
}
std::vector<std::shared_ptr<StepDetail>> RunResponse::getSteps() const
{
    return m_Steps;
}


void RunResponse::setSteps(const std::vector<std::shared_ptr<StepDetail>>& value)
{
    m_Steps = value;
    m_StepsIsSet = true;
}

bool RunResponse::stepsIsSet() const
{
    return m_StepsIsSet;
}

void RunResponse::unsetSteps()
{
    m_StepsIsSet = false;
}
std::shared_ptr<Usage> RunResponse::getUsage() const
{
    return m_Usage;
}


void RunResponse::setUsage(const std::shared_ptr<Usage>& value)
{
    m_Usage = value;
    m_UsageIsSet = true;
}

bool RunResponse::usageIsSet() const
{
    return m_UsageIsSet;
}

void RunResponse::unsetUsage()
{
    m_UsageIsSet = false;
}

}
}
}
}


