/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FirecrawlAgent/model/StepDetail.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

StepDetail::StepDetail()
{
    m_Text = utility::conversions::to_string_t("");
    m_TextIsSet = false;
    m_ToolCallsIsSet = false;
    m_ToolResultsIsSet = false;
}

StepDetail::~StepDetail()
{
}

void StepDetail::validate()
{
    // TODO: implement validation
}

web::json::value StepDetail::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_TextIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("text"))] = ModelBase::toJson(m_Text);
    }
    if(m_ToolCallsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("toolCalls"))] = ModelBase::toJson(m_ToolCalls);
    }
    if(m_ToolResultsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("toolResults"))] = ModelBase::toJson(m_ToolResults);
    }

    return val;
}

bool StepDetail::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("text")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setText;
            ok &= ModelBase::fromJson(fieldValue, refVal_setText);
            setText(refVal_setText);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("toolCalls"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("toolCalls")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<StepDetail_toolCalls_inner>> refVal_setToolCalls;
            ok &= ModelBase::fromJson(fieldValue, refVal_setToolCalls);
            setToolCalls(refVal_setToolCalls);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("toolResults"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("toolResults")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<StepDetail_toolResults_inner>> refVal_setToolResults;
            ok &= ModelBase::fromJson(fieldValue, refVal_setToolResults);
            setToolResults(refVal_setToolResults);
            
        }
    }
    return ok;
}

void StepDetail::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_TextIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("text")), m_Text));
    }
    if(m_ToolCallsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("toolCalls")), m_ToolCalls));
    }
    if(m_ToolResultsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("toolResults")), m_ToolResults));
    }
}

bool StepDetail::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("text"))))
    {
        utility::string_t refVal_setText;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("text"))), refVal_setText );
        setText(refVal_setText);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("toolCalls"))))
    {
        std::vector<std::shared_ptr<StepDetail_toolCalls_inner>> refVal_setToolCalls;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("toolCalls"))), refVal_setToolCalls );
        setToolCalls(refVal_setToolCalls);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("toolResults"))))
    {
        std::vector<std::shared_ptr<StepDetail_toolResults_inner>> refVal_setToolResults;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("toolResults"))), refVal_setToolResults );
        setToolResults(refVal_setToolResults);
    }
    return ok;
}


utility::string_t StepDetail::getText() const
{
    return m_Text;
}


void StepDetail::setText(const utility::string_t& value)
{
    m_Text = value;
    m_TextIsSet = true;
}

bool StepDetail::textIsSet() const
{
    return m_TextIsSet;
}

void StepDetail::unsetText()
{
    m_TextIsSet = false;
}
std::vector<std::shared_ptr<StepDetail_toolCalls_inner>> StepDetail::getToolCalls() const
{
    return m_ToolCalls;
}


void StepDetail::setToolCalls(const std::vector<std::shared_ptr<StepDetail_toolCalls_inner>>& value)
{
    m_ToolCalls = value;
    m_ToolCallsIsSet = true;
}

bool StepDetail::toolCallsIsSet() const
{
    return m_ToolCallsIsSet;
}

void StepDetail::unsetToolCalls()
{
    m_ToolCallsIsSet = false;
}
std::vector<std::shared_ptr<StepDetail_toolResults_inner>> StepDetail::getToolResults() const
{
    return m_ToolResults;
}


void StepDetail::setToolResults(const std::vector<std::shared_ptr<StepDetail_toolResults_inner>>& value)
{
    m_ToolResults = value;
    m_ToolResultsIsSet = true;
}

bool StepDetail::toolResultsIsSet() const
{
    return m_ToolResultsIsSet;
}

void StepDetail::unsetToolResults()
{
    m_ToolResultsIsSet = false;
}

}
}
}
}


