/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FirecrawlAgent/model/SubAgentConfig.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

SubAgentConfig::SubAgentConfig()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Description = utility::conversions::to_string_t("");
    m_DescriptionIsSet = false;
    m_Instructions = utility::conversions::to_string_t("");
    m_InstructionsIsSet = false;
    m_ModelIsSet = false;
    m_ToolsIsSet = false;
    m_SkillsIsSet = false;
    m_MaxSteps = 0;
    m_MaxStepsIsSet = false;
}

SubAgentConfig::~SubAgentConfig()
{
}

void SubAgentConfig::validate()
{
    // TODO: implement validation
}

web::json::value SubAgentConfig::toJson() const
{
    web::json::value val = web::json::value::object();
    if(m_IdIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_DescriptionIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("description"))] = ModelBase::toJson(m_Description);
    }
    if(m_InstructionsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("instructions"))] = ModelBase::toJson(m_Instructions);
    }
    if(m_ModelIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("model"))] = ModelBase::toJson(m_Model);
    }
    if(m_ToolsIsSet)
    {
        
        std::vector<utility::string_t> refVal = fromToolsEnum(m_Tools);
        val[utility::conversions::to_string_t(_XPLATSTR("tools"))] = ModelBase::toJson(refVal);
        
    }
    if(m_SkillsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("skills"))] = ModelBase::toJson(m_Skills);
    }
    if(m_MaxStepsIsSet)
    {
        
        val[utility::conversions::to_string_t(_XPLATSTR("maxSteps"))] = ModelBase::toJson(m_MaxSteps);
    }

    return val;
}

bool SubAgentConfig::fromJson(const web::json::value& val)
{
    bool ok = true;
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("description")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDescription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDescription);
            setDescription(refVal_setDescription);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("instructions"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("instructions")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setInstructions;
            ok &= ModelBase::fromJson(fieldValue, refVal_setInstructions);
            setInstructions(refVal_setInstructions);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("model"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("model")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<ModelConfig> refVal_setModel;
            ok &= ModelBase::fromJson(fieldValue, refVal_setModel);
            setModel(refVal_setModel);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("tools"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("tools")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setTools;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTools);
            
            setTools(toToolsEnum(refVal_setTools));
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("skills"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("skills")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setSkills;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSkills);
            setSkills(refVal_setSkills);
            
        }
    }
    if(val.has_field(utility::conversions::to_string_t(_XPLATSTR("maxSteps"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(_XPLATSTR("maxSteps")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setMaxSteps;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMaxSteps);
            setMaxSteps(refVal_setMaxSteps);
            
        }
    }
    return ok;
}

void SubAgentConfig::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("name")), m_Name));
    }
    if(m_DescriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("description")), m_Description));
    }
    if(m_InstructionsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("instructions")), m_Instructions));
    }
    if(m_ModelIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("model")), m_Model));
    }
    if(m_ToolsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("tools")), fromToolsEnum(m_Tools)));
            }
    if(m_SkillsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("skills")), m_Skills));
    }
    if(m_MaxStepsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(_XPLATSTR("maxSteps")), m_MaxSteps));
    }
}

bool SubAgentConfig::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(_XPLATSTR(".")))
    {
        namePrefix += utility::conversions::to_string_t(_XPLATSTR("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("description"))))
    {
        utility::string_t refVal_setDescription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("description"))), refVal_setDescription );
        setDescription(refVal_setDescription);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("instructions"))))
    {
        utility::string_t refVal_setInstructions;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("instructions"))), refVal_setInstructions );
        setInstructions(refVal_setInstructions);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("model"))))
    {
        std::shared_ptr<ModelConfig> refVal_setModel;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("model"))), refVal_setModel );
        setModel(refVal_setModel);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("tools"))))
    {
        std::vector<utility::string_t> refVal_setTools;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("tools"))), refVal_setTools );
        setTools(toToolsEnum(refVal_setTools));
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("skills"))))
    {
        std::vector<utility::string_t> refVal_setSkills;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("skills"))), refVal_setSkills );
        setSkills(refVal_setSkills);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(_XPLATSTR("maxSteps"))))
    {
        int32_t refVal_setMaxSteps;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(_XPLATSTR("maxSteps"))), refVal_setMaxSteps );
        setMaxSteps(refVal_setMaxSteps);
    }
    return ok;
}

SubAgentConfig::ToolsEnum SubAgentConfig::toToolsEnum(const utility::string_t& value) const
{
    
    if (value == utility::conversions::to_string_t("search")) {
        return ToolsEnum::SEARCH;
    }
    
    if (value == utility::conversions::to_string_t("scrape")) {
        return ToolsEnum::SCRAPE;
    }
    
    if (value == utility::conversions::to_string_t("interact")) {
        return ToolsEnum::INTERACT;
    }
    
    if (value == utility::conversions::to_string_t("map")) {
        return ToolsEnum::MAP;
    }
    
    throw std::invalid_argument("Invalid value for conversion to std::vector<ToolsEnum>");
}

const utility::string_t SubAgentConfig::fromToolsEnum(const ToolsEnum value) const
{
    switch(value)
    {
        
        case ToolsEnum::SEARCH: return utility::conversions::to_string_t("search");
        
        case ToolsEnum::SCRAPE: return utility::conversions::to_string_t("scrape");
        
        case ToolsEnum::INTERACT: return utility::conversions::to_string_t("interact");
        
        case ToolsEnum::MAP: return utility::conversions::to_string_t("map");
        
    }
}

std::vector<utility::string_t> SubAgentConfig::fromToolsEnum(const std::vector<ToolsEnum>& value) const
{
    std::vector<utility::string_t> ret;
    for (auto it = value.begin(); it != value.end(); it++) {
        ret.push_back(fromToolsEnum(*it));
    }
    return ret;
}

std::vector<SubAgentConfig::ToolsEnum> SubAgentConfig::toToolsEnum(const std::vector<utility::string_t>& value) const
{
    std::vector<ToolsEnum> ret;
    for (auto it = value.begin(); it != value.end(); it++) {
        ret.push_back(toToolsEnum(*it));
    }
    return ret;
}

utility::string_t SubAgentConfig::getId() const
{
    return m_Id;
}


void SubAgentConfig::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool SubAgentConfig::idIsSet() const
{
    return m_IdIsSet;
}

void SubAgentConfig::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t SubAgentConfig::getName() const
{
    return m_Name;
}


void SubAgentConfig::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool SubAgentConfig::nameIsSet() const
{
    return m_NameIsSet;
}

void SubAgentConfig::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t SubAgentConfig::getDescription() const
{
    return m_Description;
}


void SubAgentConfig::setDescription(const utility::string_t& value)
{
    m_Description = value;
    m_DescriptionIsSet = true;
}

bool SubAgentConfig::descriptionIsSet() const
{
    return m_DescriptionIsSet;
}

void SubAgentConfig::unsetDescription()
{
    m_DescriptionIsSet = false;
}
utility::string_t SubAgentConfig::getInstructions() const
{
    return m_Instructions;
}


void SubAgentConfig::setInstructions(const utility::string_t& value)
{
    m_Instructions = value;
    m_InstructionsIsSet = true;
}

bool SubAgentConfig::instructionsIsSet() const
{
    return m_InstructionsIsSet;
}

void SubAgentConfig::unsetInstructions()
{
    m_InstructionsIsSet = false;
}
std::shared_ptr<ModelConfig> SubAgentConfig::getModel() const
{
    return m_Model;
}


void SubAgentConfig::setModel(const std::shared_ptr<ModelConfig>& value)
{
    m_Model = value;
    m_ModelIsSet = true;
}

bool SubAgentConfig::modelIsSet() const
{
    return m_ModelIsSet;
}

void SubAgentConfig::unsetModel()
{
    m_ModelIsSet = false;
}
std::vector<SubAgentConfig::ToolsEnum> SubAgentConfig::getTools() const
{
    return m_Tools;
}


void SubAgentConfig::setTools(const std::vector<ToolsEnum> value)
{
    m_Tools = value;
    m_ToolsIsSet = true;
}

bool SubAgentConfig::toolsIsSet() const
{
    return m_ToolsIsSet;
}

void SubAgentConfig::unsetTools()
{
    m_ToolsIsSet = false;
}
std::vector<utility::string_t> SubAgentConfig::getSkills() const
{
    return m_Skills;
}


void SubAgentConfig::setSkills(const std::vector<utility::string_t>& value)
{
    m_Skills = value;
    m_SkillsIsSet = true;
}

bool SubAgentConfig::skillsIsSet() const
{
    return m_SkillsIsSet;
}

void SubAgentConfig::unsetSkills()
{
    m_SkillsIsSet = false;
}
int32_t SubAgentConfig::getMaxSteps() const
{
    return m_MaxSteps;
}

void SubAgentConfig::setMaxSteps(int32_t value)
{
    m_MaxSteps = value;
    m_MaxStepsIsSet = true;
}

bool SubAgentConfig::maxStepsIsSet() const
{
    return m_MaxStepsIsSet;
}

void SubAgentConfig::unsetMaxSteps()
{
    m_MaxStepsIsSet = false;
}

}
}
}
}


