/* tslint:disable */
/* eslint-disable */
/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepDetailToolCallsInner } from './StepDetailToolCallsInner';
import {
    StepDetailToolCallsInnerFromJSON,
    StepDetailToolCallsInnerFromJSONTyped,
    StepDetailToolCallsInnerToJSON,
    StepDetailToolCallsInnerToJSONTyped,
} from './StepDetailToolCallsInner';
import type { StepDetailToolResultsInner } from './StepDetailToolResultsInner';
import {
    StepDetailToolResultsInnerFromJSON,
    StepDetailToolResultsInnerFromJSONTyped,
    StepDetailToolResultsInnerToJSON,
    StepDetailToolResultsInnerToJSONTyped,
} from './StepDetailToolResultsInner';

/**
 * 
 * @export
 * @interface StepDetail
 */
export interface StepDetail {
    /**
     * 
     * @type {string}
     * @memberof StepDetail
     */
    text?: string;
    /**
     * 
     * @type {Array<StepDetailToolCallsInner>}
     * @memberof StepDetail
     */
    toolCalls?: Array<StepDetailToolCallsInner>;
    /**
     * 
     * @type {Array<StepDetailToolResultsInner>}
     * @memberof StepDetail
     */
    toolResults?: Array<StepDetailToolResultsInner>;
}

/**
 * Check if a given object implements the StepDetail interface.
 */
export function instanceOfStepDetail(value: object): value is StepDetail {
    return true;
}

export function StepDetailFromJSON(json: any): StepDetail {
    return StepDetailFromJSONTyped(json, false);
}

export function StepDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'toolCalls': json['toolCalls'] == null ? undefined : ((json['toolCalls'] as Array<any>).map(StepDetailToolCallsInnerFromJSON)),
        'toolResults': json['toolResults'] == null ? undefined : ((json['toolResults'] as Array<any>).map(StepDetailToolResultsInnerFromJSON)),
    };
}

export function StepDetailToJSON(json: any): StepDetail {
    return StepDetailToJSONTyped(json, false);
}

export function StepDetailToJSONTyped(value?: StepDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'toolCalls': value['toolCalls'] == null ? undefined : ((value['toolCalls'] as Array<any>).map(StepDetailToolCallsInnerToJSON)),
        'toolResults': value['toolResults'] == null ? undefined : ((value['toolResults'] as Array<any>).map(StepDetailToolResultsInnerToJSON)),
    };
}

