/*
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firecrawl.agent.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkerProgressStepLogInner
 */
public class WorkerProgressStepLogInnerTest {
    private final WorkerProgressStepLogInner model = new WorkerProgressStepLogInner();

    /**
     * Model tests for WorkerProgressStepLogInner
     */
    @Test
    public void testWorkerProgressStepLogInner() {
        // TODO: test WorkerProgressStepLogInner
    }

    /**
     * Test the property 'tool'
     */
    @Test
    public void toolTest() {
        // TODO: test tool
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

}
