# NOTE: This file is auto generated by OpenAPI Generator 7.21.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule FirecrawlAgentAPI.Model.ModelConfig do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :model
  ]

  @type t :: %__MODULE__{
    :provider => String.t | nil,
    :model => String.t | nil
  }

  def decode(value) do
    value
  end
end

