#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FirecrawlAgent' -name 'AgentEventOneOf' {
    Context 'AgentEventOneOf' {
        It 'Initialize-AgentEventOneOf' {
            # a simple test to create an object
            #$NewObject = Initialize-AgentEventOneOf -Type "TEST_VALUE" -Content "TEST_VALUE"
            #$NewObject | Should -BeOfType AgentEventOneOf
            #$NewObject.property | Should -Be 0
        }
    }
}
