#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FirecrawlAgent' -name 'ErrorResponse' {
    Context 'ErrorResponse' {
        It 'Initialize-ErrorResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-ErrorResponse -VarError "TEST_VALUE"
            #$NewObject | Should -BeOfType ErrorResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
