#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FirecrawlAgent' -name 'ExportedSkill' {
    Context 'ExportedSkill' {
        It 'Initialize-ExportedSkill' {
            # a simple test to create an object
            #$NewObject = Initialize-ExportedSkill -Name "TEST_VALUE" -SkillMd "TEST_VALUE" -Workflow "TEST_VALUE" -Schema "TEST_VALUE"
            #$NewObject | Should -BeOfType ExportedSkill
            #$NewObject.property | Should -Be 0
        }
    }
}
