#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FirecrawlAgent' -name 'StepDetailToolCallsInner' {
    Context 'StepDetailToolCallsInner' {
        It 'Initialize-StepDetailToolCallsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-StepDetailToolCallsInner -Name "TEST_VALUE" -VarInput "TEST_VALUE"
            #$NewObject | Should -BeOfType StepDetailToolCallsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
