#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FirecrawlAgent' -name 'StepDetailToolResultsInner' {
    Context 'StepDetailToolResultsInner' {
        It 'Initialize-StepDetailToolResultsInner' {
            # a simple test to create an object
            #$NewObject = Initialize-StepDetailToolResultsInner -Name "TEST_VALUE" -Output "TEST_VALUE"
            #$NewObject | Should -BeOfType StepDetailToolResultsInner
            #$NewObject.property | Should -Be 0
        }
    }
}
