#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FirecrawlAgent' -name 'Usage' {
    Context 'Usage' {
        It 'Initialize-Usage' {
            # a simple test to create an object
            #$NewObject = Initialize-Usage -InputTokens "TEST_VALUE" -OutputTokens "TEST_VALUE" -TotalTokens "TEST_VALUE"
            #$NewObject | Should -BeOfType Usage
            #$NewObject.property | Should -Be 0
        }
    }
}
