#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'FirecrawlAgent' -name 'WorkerProgressStepLogInner' {
    Context 'WorkerProgressStepLogInner' {
        It 'Initialize-WorkerProgressStepLogInner' {
            # a simple test to create an object
            #$NewObject = Initialize-WorkerProgressStepLogInner -Tool "TEST_VALUE" -Detail "TEST_VALUE"
            #$NewObject | Should -BeOfType WorkerProgressStepLogInner
            #$NewObject.property | Should -Be 0
        }
    }
}
