# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StepDetailToolCallsInner")

model_instance <- StepDetailToolCallsInner$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("input", {
  # tests for the property `input` (object)

  # uncomment below to test the property
  #expect_equal(model.instance$`input`, "EXPECTED_RESULT")
})
