# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AgentEventOneOf5")

model_instance <- AgentEventOneOf5$new()

test_that("type", {
  # tests for the property `type` (AnyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("error", {
  # tests for the property `error` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})
