# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubAgentConfig")

model_instance <- SubAgentConfig$new()

test_that("id", {
  # tests for the property `id` (character)
  # Unique identifier for this sub-agent (used as the tool name suffix).

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # Human-readable name shown in the tool description.

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)
  # What this sub-agent does. Included in the tool description for the orchestrator.

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("instructions", {
  # tests for the property `instructions` (character)
  # Custom instructions appended to the sub-agent&#39;s system prompt.

  # uncomment below to test the property
  #expect_equal(model.instance$`instructions`, "EXPECTED_RESULT")
})

test_that("model", {
  # tests for the property `model` (ModelConfig)

  # uncomment below to test the property
  #expect_equal(model.instance$`model`, "EXPECTED_RESULT")
})

test_that("tools", {
  # tests for the property `tools` (array[character])
  # Firecrawl tools available to this sub-agent.

  # uncomment below to test the property
  #expect_equal(model.instance$`tools`, "EXPECTED_RESULT")
})

test_that("skills", {
  # tests for the property `skills` (array[character])
  # Skills to pre-load for this sub-agent.

  # uncomment below to test the property
  #expect_equal(model.instance$`skills`, "EXPECTED_RESULT")
})

test_that("maxSteps", {
  # tests for the property `maxSteps` (integer)
  # Maximum steps before the sub-agent stops.

  # uncomment below to test the property
  #expect_equal(model.instance$`maxSteps`, "EXPECTED_RESULT")
})
