/* tslint:disable */
/* eslint-disable */
/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentEventOneOf5
 */
export interface AgentEventOneOf5 {
    /**
     * 
     * @type {any}
     * @memberof AgentEventOneOf5
     */
    type?: any | null;
    /**
     * 
     * @type {string}
     * @memberof AgentEventOneOf5
     */
    error?: string;
}

/**
 * Check if a given object implements the AgentEventOneOf5 interface.
 */
export function instanceOfAgentEventOneOf5(value: object): value is AgentEventOneOf5 {
    return true;
}

export function AgentEventOneOf5FromJSON(json: any): AgentEventOneOf5 {
    return AgentEventOneOf5FromJSONTyped(json, false);
}

export function AgentEventOneOf5FromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentEventOneOf5 {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AgentEventOneOf5ToJSON(json: any): AgentEventOneOf5 {
    return AgentEventOneOf5ToJSONTyped(json, false);
}

export function AgentEventOneOf5ToJSONTyped(value?: AgentEventOneOf5 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'error': value['error'],
    };
}

