/* tslint:disable */
/* eslint-disable */
/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelConfig } from './ModelConfig';
import {
    ModelConfigFromJSON,
    ModelConfigFromJSONTyped,
    ModelConfigToJSON,
    ModelConfigToJSONTyped,
} from './ModelConfig';

/**
 * 
 * @export
 * @interface RunRequest
 */
export interface RunRequest {
    /**
     * The research task or question.
     * @type {string}
     * @memberof RunRequest
     */
    prompt: string;
    /**
     * If true, response is an SSE stream of AgentEvent objects.
     * @type {boolean}
     * @memberof RunRequest
     */
    stream?: boolean;
    /**
     * Desired output format. If set, agent will format data accordingly.
     * @type {RunRequestFormatEnum}
     * @memberof RunRequest
     */
    format?: RunRequestFormatEnum;
    /**
     * JSON Schema for structured output (used with format=json).
     * @type {object}
     * @memberof RunRequest
     */
    schema?: object;
    /**
     * Column names for CSV output.
     * @type {Array<string>}
     * @memberof RunRequest
     */
    columns?: Array<string>;
    /**
     * Seed URLs to start from instead of searching.
     * @type {Array<string>}
     * @memberof RunRequest
     */
    urls?: Array<string>;
    /**
     * 
     * @type {ModelConfig}
     * @memberof RunRequest
     */
    model?: ModelConfig;
    /**
     * 
     * @type {ModelConfig}
     * @memberof RunRequest
     */
    subAgentModel?: ModelConfig;
    /**
     * Maximum agent steps before stopping.
     * @type {number}
     * @memberof RunRequest
     */
    maxSteps?: number;
    /**
     * Skills to pre-load for this run.
     * @type {Array<string>}
     * @memberof RunRequest
     */
    skills?: Array<string>;
}


/**
 * @export
 */
export const RunRequestFormatEnum = {
    Json: 'json',
    Csv: 'csv',
    Markdown: 'markdown'
} as const;
export type RunRequestFormatEnum = typeof RunRequestFormatEnum[keyof typeof RunRequestFormatEnum];


/**
 * Check if a given object implements the RunRequest interface.
 */
export function instanceOfRunRequest(value: object): value is RunRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function RunRequestFromJSON(json: any): RunRequest {
    return RunRequestFromJSONTyped(json, false);
}

export function RunRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'stream': json['stream'] == null ? undefined : json['stream'],
        'format': json['format'] == null ? undefined : json['format'],
        'schema': json['schema'] == null ? undefined : json['schema'],
        'columns': json['columns'] == null ? undefined : json['columns'],
        'urls': json['urls'] == null ? undefined : json['urls'],
        'model': json['model'] == null ? undefined : ModelConfigFromJSON(json['model']),
        'subAgentModel': json['subAgentModel'] == null ? undefined : ModelConfigFromJSON(json['subAgentModel']),
        'maxSteps': json['maxSteps'] == null ? undefined : json['maxSteps'],
        'skills': json['skills'] == null ? undefined : json['skills'],
    };
}

export function RunRequestToJSON(json: any): RunRequest {
    return RunRequestToJSONTyped(json, false);
}

export function RunRequestToJSONTyped(value?: RunRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'stream': value['stream'],
        'format': value['format'],
        'schema': value['schema'],
        'columns': value['columns'],
        'urls': value['urls'],
        'model': ModelConfigToJSON(value['model']),
        'subAgentModel': ModelConfigToJSON(value['subAgentModel']),
        'maxSteps': value['maxSteps'],
        'skills': value['skills'],
    };
}

