/* tslint:disable */
/* eslint-disable */
/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkerProgressStepLogInner } from './WorkerProgressStepLogInner';
import {
    WorkerProgressStepLogInnerFromJSON,
    WorkerProgressStepLogInnerFromJSONTyped,
    WorkerProgressStepLogInnerToJSON,
    WorkerProgressStepLogInnerToJSONTyped,
} from './WorkerProgressStepLogInner';

/**
 * 
 * @export
 * @interface WorkerProgress
 */
export interface WorkerProgress {
    /**
     * 
     * @type {string}
     * @memberof WorkerProgress
     */
    id?: string;
    /**
     * 
     * @type {WorkerProgressStatusEnum}
     * @memberof WorkerProgress
     */
    status?: WorkerProgressStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof WorkerProgress
     */
    steps?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkerProgress
     */
    currentTool?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkerProgress
     */
    tokens?: number;
    /**
     * 
     * @type {Array<WorkerProgressStepLogInner>}
     * @memberof WorkerProgress
     */
    stepLog?: Array<WorkerProgressStepLogInner>;
}


/**
 * @export
 */
export const WorkerProgressStatusEnum = {
    Running: 'running',
    Done: 'done',
    Error: 'error'
} as const;
export type WorkerProgressStatusEnum = typeof WorkerProgressStatusEnum[keyof typeof WorkerProgressStatusEnum];


/**
 * Check if a given object implements the WorkerProgress interface.
 */
export function instanceOfWorkerProgress(value: object): value is WorkerProgress {
    return true;
}

export function WorkerProgressFromJSON(json: any): WorkerProgress {
    return WorkerProgressFromJSONTyped(json, false);
}

export function WorkerProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkerProgress {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'steps': json['steps'] == null ? undefined : json['steps'],
        'currentTool': json['currentTool'] == null ? undefined : json['currentTool'],
        'tokens': json['tokens'] == null ? undefined : json['tokens'],
        'stepLog': json['stepLog'] == null ? undefined : ((json['stepLog'] as Array<any>).map(WorkerProgressStepLogInnerFromJSON)),
    };
}

export function WorkerProgressToJSON(json: any): WorkerProgress {
    return WorkerProgressToJSONTyped(json, false);
}

export function WorkerProgressToJSONTyped(value?: WorkerProgress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'steps': value['steps'],
        'currentTool': value['currentTool'],
        'tokens': value['tokens'],
        'stepLog': value['stepLog'] == null ? undefined : ((value['stepLog'] as Array<any>).map(WorkerProgressStepLogInnerToJSON)),
    };
}

