/* tslint:disable */
/* eslint-disable */
/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkerProgressStepLogInner
 */
export interface WorkerProgressStepLogInner {
    /**
     * 
     * @type {string}
     * @memberof WorkerProgressStepLogInner
     */
    tool?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkerProgressStepLogInner
     */
    detail?: string;
}

/**
 * Check if a given object implements the WorkerProgressStepLogInner interface.
 */
export function instanceOfWorkerProgressStepLogInner(value: object): value is WorkerProgressStepLogInner {
    return true;
}

export function WorkerProgressStepLogInnerFromJSON(json: any): WorkerProgressStepLogInner {
    return WorkerProgressStepLogInnerFromJSONTyped(json, false);
}

export function WorkerProgressStepLogInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkerProgressStepLogInner {
    if (json == null) {
        return json;
    }
    return {
        
        'tool': json['tool'] == null ? undefined : json['tool'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function WorkerProgressStepLogInnerToJSON(json: any): WorkerProgressStepLogInner {
    return WorkerProgressStepLogInnerToJSONTyped(json, false);
}

export function WorkerProgressStepLogInnerToJSONTyped(value?: WorkerProgressStepLogInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tool': value['tool'],
        'detail': value['detail'],
    };
}

