# coding: utf-8

"""
    Firecrawl Agent API

    AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firecrawl_agent.models.agent_event import AgentEvent

class TestAgentEvent(unittest.TestCase):
    """AgentEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentEvent:
        """Test AgentEvent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentEvent`
        """
        model = AgentEvent()
        if include_optional:
            return AgentEvent(
                type = None,
                content = '',
                name = '',
                input = firecrawl_agent.models.input.input(),
                output = firecrawl_agent.models.input.input(),
                usage = firecrawl_agent.models.usage.Usage(
                    input_tokens = 56, 
                    output_tokens = 56, 
                    total_tokens = 56, ),
                text = '',
                steps = [
                    firecrawl_agent.models.step_detail.StepDetail(
                        text = '', 
                        tool_calls = [
                            firecrawl_agent.models.step_detail_tool_calls_inner.StepDetail_toolCalls_inner(
                                name = '', 
                                input = firecrawl_agent.models.input.input(), )
                            ], 
                        tool_results = [
                            firecrawl_agent.models.step_detail_tool_results_inner.StepDetail_toolResults_inner(
                                name = '', 
                                output = firecrawl_agent.models.output.output(), )
                            ], )
                    ],
                error = ''
            )
        else:
            return AgentEvent(
        )
        """

    def testAgentEvent(self):
        """Test AgentEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
