# coding: utf-8

"""
    Firecrawl Agent API

    AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firecrawl_agent.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_worker_progress(self) -> None:
        """Test case for get_worker_progress

        Get parallel worker progress
        """
        pass

    def test_list_skills(self) -> None:
        """Test case for list_skills

        List available skills
        """
        pass

    def test_run(self) -> None:
        """Test case for run

        Run the agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
