# coding: utf-8

"""
    Firecrawl Agent API

    AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from firecrawl_agent.models.step_detail_tool_calls_inner import StepDetailToolCallsInner

class TestStepDetailToolCallsInner(unittest.TestCase):
    """StepDetailToolCallsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StepDetailToolCallsInner:
        """Test StepDetailToolCallsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StepDetailToolCallsInner`
        """
        model = StepDetailToolCallsInner()
        if include_optional:
            return StepDetailToolCallsInner(
                name = '',
                input = firecrawl_agent.models.input.input()
            )
        else:
            return StepDetailToolCallsInner(
        )
        """

    def testStepDetailToolCallsInner(self):
        """Test StepDetailToolCallsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
