=begin
#Firecrawl Agent API

#AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FirecrawlAgent::Usage
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FirecrawlAgent::Usage do
  #let(:instance) { FirecrawlAgent::Usage.new }

  describe 'test an instance of Usage' do
    it 'should create an instance of Usage' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FirecrawlAgent::Usage)
    end
  end

  describe 'test attribute "input_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "output_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "total_tokens"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
