=begin
#Firecrawl Agent API

#AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FirecrawlAgent::Skill
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe FirecrawlAgent::Skill do
  #let(:instance) { FirecrawlAgent::Skill.new }

  describe 'test an instance of Skill' do
    it 'should create an instance of Skill' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(FirecrawlAgent::Skill)
    end
  end

  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "description"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "resources"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
