/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.firecrawl.agent.model


case class ModelConfig(
  /* LLM provider. */
  provider: Option[ModelConfigEnums.Provider] = None,
  /* Model identifier (e.g. \"gemini-3-flash-preview\", \"claude-sonnet-4-6\"). */
  model: Option[String] = None
)

object ModelConfigEnums {

  type Provider = Provider.Value
  object Provider extends Enumeration {
    val Anthropic = Value("anthropic")
    val Openai = Value("openai")
    val Google = Value("google")
    val Gateway = Value("gateway")
  }

}
