//
// AgentEventOneOf4.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AgentEventOneOf4: Sendable, Codable, Hashable {

    public var type: JSONValue?
    public var text: String?
    public var steps: [StepDetail]?
    public var usage: Usage?

    public init(type: JSONValue? = nil, text: String? = nil, steps: [StepDetail]? = nil, usage: Usage? = nil) {
        self.type = type
        self.text = text
        self.steps = steps
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case text
        case steps
        case usage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(steps, forKey: .steps)
        try container.encodeIfPresent(usage, forKey: .usage)
    }
}

