/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.firecrawl.agent.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.firecrawl.agent.models.ExportedSkill

class ExportedSkillTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExportedSkill
        //val modelInstance = ExportedSkill()

        // to test the property `name` - Slug identifier for the skill.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `skillMd` - Full SKILL.md content with frontmatter.
        should("test skillMd") {
            // uncomment below to test the property
            //modelInstance.skillMd shouldBe ("TODO")
        }

        // to test the property `workflow` - Deterministic workflow.mjs script content.
        should("test workflow") {
            // uncomment below to test the property
            //modelInstance.workflow shouldBe ("TODO")
        }

        // to test the property `schema` - Expected output schema.json content.
        should("test schema") {
            // uncomment below to test the property
            //modelInstance.schema shouldBe ("TODO")
        }

    }
}
