/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExportedSkill : A reusable skill package generated from the run's tool call history. Present when exportSkill=true in the request. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportedSkill {
    /// Slug identifier for the skill.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Full SKILL.md content with frontmatter.
    #[serde(rename = "skillMd", skip_serializing_if = "Option::is_none")]
    pub skill_md: Option<String>,
    /// Deterministic workflow.mjs script content.
    #[serde(rename = "workflow", skip_serializing_if = "Option::is_none")]
    pub workflow: Option<String>,
    /// Expected output schema.json content.
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
}

impl ExportedSkill {
    /// A reusable skill package generated from the run's tool call history. Present when exportSkill=true in the request. 
    pub fn new() -> ExportedSkill {
        ExportedSkill {
            name: None,
            skill_md: None,
            workflow: None,
            schema: None,
        }
    }
}

