/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunRequest {
    /// The research task or question.
    #[serde(rename = "prompt")]
    pub prompt: String,
    /// If true, response is an SSE stream of AgentEvent objects.
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    /// Desired output format. If set, agent will format data accordingly.
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<Format>,
    /// JSON schema that serves as both a research plan and output format. The agent treats each field as a data point to collect during research. Array fields mean \"find all items.\" The final output is compiled into this exact shape. Used with format=json. 
    #[serde(rename = "schema", skip_serializing_if = "Option::is_none")]
    pub schema: Option<serde_json::Value>,
    /// Column names for CSV output. Each column acts as a required data point the agent will research. The final CSV contains one column per entry. 
    #[serde(rename = "columns", skip_serializing_if = "Option::is_none")]
    pub columns: Option<Vec<String>>,
    /// Seed URLs to start from instead of searching.
    #[serde(rename = "urls", skip_serializing_if = "Option::is_none")]
    pub urls: Option<Vec<String>>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::ModelConfig>>,
    #[serde(rename = "subAgentModel", skip_serializing_if = "Option::is_none")]
    pub sub_agent_model: Option<Box<models::ModelConfig>>,
    /// Maximum agent steps before stopping.
    #[serde(rename = "maxSteps", skip_serializing_if = "Option::is_none")]
    pub max_steps: Option<i32>,
    /// Skills to pre-load for this run.
    #[serde(rename = "skills", skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<String>>,
    /// Per-skill custom instructions. Keys are skill names, values are instruction strings appended when the skill is loaded. 
    #[serde(rename = "skillInstructions", skip_serializing_if = "Option::is_none")]
    pub skill_instructions: Option<std::collections::HashMap<String, String>>,
    /// Sub-agents available during this run. Each sub-agent becomes a tool the orchestrator can delegate tasks to. 
    #[serde(rename = "subAgents", skip_serializing_if = "Option::is_none")]
    pub sub_agents: Option<Vec<models::SubAgentConfig>>,
    /// When true, post-processes the run into a reusable skill package (SKILL.md + workflow.mjs + schema.json) returned in the response. 
    #[serde(rename = "exportSkill", skip_serializing_if = "Option::is_none")]
    pub export_skill: Option<bool>,
}

impl RunRequest {
    pub fn new(prompt: String) -> RunRequest {
        RunRequest {
            prompt,
            stream: None,
            format: None,
            schema: None,
            columns: None,
            urls: None,
            model: None,
            sub_agent_model: None,
            max_steps: None,
            skills: None,
            skill_instructions: None,
            sub_agents: None,
            export_skill: None,
        }
    }
}
/// Desired output format. If set, agent will format data accordingly.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "json")]
    Json,
    #[serde(rename = "csv")]
    Csv,
    #[serde(rename = "markdown")]
    Markdown,
}

impl Default for Format {
    fn default() -> Format {
        Self::Json
    }
}

