/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "FirecrawlAgent/model/AgentEvent.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

void AgentEvent::validate()
{
    // TODO: implement validation
}

const AgentEvent::VariantType& AgentEvent::getVariant() const
{
    return m_variantValue;
}

void AgentEvent::setVariant(AgentEvent::VariantType value)
{
    m_variantValue = value;
}

web::json::value AgentEvent::toJson() const
{
    web::json::value val = web::json::value::object();

    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (std::is_same_v<T, std::monostate>) {
            val = web::json::value::null();
        } else {
            val = arg.toJson();
        }
    }, m_variantValue);

    return val;
}

void AgentEvent::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    std::visit([&](auto&& arg) {
        using T = std::decay_t<decltype(arg)>;
        if constexpr (!std::is_same_v<T, std::monostate>) {
          arg.toMultipart(multipart, prefix);
        }
    }, m_variantValue);
}

template bool AgentEvent::fromJson<AgentEvent_oneOf>(const web::json::value& json);
template bool AgentEvent::fromMultiPart<AgentEvent_oneOf>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool AgentEvent::fromJson<AgentEvent_oneOf_1>(const web::json::value& json);
template bool AgentEvent::fromMultiPart<AgentEvent_oneOf_1>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool AgentEvent::fromJson<AgentEvent_oneOf_2>(const web::json::value& json);
template bool AgentEvent::fromMultiPart<AgentEvent_oneOf_2>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool AgentEvent::fromJson<AgentEvent_oneOf_3>(const web::json::value& json);
template bool AgentEvent::fromMultiPart<AgentEvent_oneOf_3>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool AgentEvent::fromJson<AgentEvent_oneOf_4>(const web::json::value& json);
template bool AgentEvent::fromMultiPart<AgentEvent_oneOf_4>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);
template bool AgentEvent::fromJson<AgentEvent_oneOf_5>(const web::json::value& json);
template bool AgentEvent::fromMultiPart<AgentEvent_oneOf_5>(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix);

}
}
}
}


