# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Skill")

model_instance <- Skill$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("resources", {
  # tests for the property `resources` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`resources`, "EXPECTED_RESULT")
})
