=begin
#Firecrawl Agent API

#AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for FirecrawlAgent::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = FirecrawlAgent::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(FirecrawlAgent::DefaultApi)
    end
  end

  # unit tests for get_worker_progress
  # Get parallel worker progress
  # Poll for progress of currently running parallel workers.
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, WorkerProgress>]
  describe 'get_worker_progress test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_skills
  # List available skills
  # Returns all discovered skills the agent can use.
  # @param [Hash] opts the optional parameters
  # @return [Array<Skill>]
  describe 'list_skills test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for run
  # Run the agent
  # Execute a web research task. Supports both streaming (SSE) and non-streaming responses. This is the single consolidated endpoint that replaces /query, /extract, and /plan. 
  # @param run_request 
  # @param [Hash] opts the optional parameters
  # @return [RunResponse]
  describe 'run test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
