// <auto-generated>
/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using FirecrawlAgent.Client;

namespace FirecrawlAgent.Model
{
    /// <summary>
    /// Server-sent event payload (when stream&#x3D;true)
    /// </summary>
    public partial class AgentEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentEvent" /> class.
        /// </summary>
        /// <param name="agentEventOneOf"></param>
        public AgentEvent(AgentEventOneOf agentEventOneOf)
        {
            AgentEventOneOf = agentEventOneOf;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentEvent" /> class.
        /// </summary>
        /// <param name="agentEventOneOf1"></param>
        public AgentEvent(AgentEventOneOf1 agentEventOneOf1)
        {
            AgentEventOneOf1 = agentEventOneOf1;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentEvent" /> class.
        /// </summary>
        /// <param name="agentEventOneOf2"></param>
        public AgentEvent(AgentEventOneOf2 agentEventOneOf2)
        {
            AgentEventOneOf2 = agentEventOneOf2;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentEvent" /> class.
        /// </summary>
        /// <param name="agentEventOneOf3"></param>
        public AgentEvent(AgentEventOneOf3 agentEventOneOf3)
        {
            AgentEventOneOf3 = agentEventOneOf3;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentEvent" /> class.
        /// </summary>
        /// <param name="agentEventOneOf4"></param>
        public AgentEvent(AgentEventOneOf4 agentEventOneOf4)
        {
            AgentEventOneOf4 = agentEventOneOf4;
            OnCreated();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentEvent" /> class.
        /// </summary>
        /// <param name="agentEventOneOf5"></param>
        public AgentEvent(AgentEventOneOf5 agentEventOneOf5)
        {
            AgentEventOneOf5 = agentEventOneOf5;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets AgentEventOneOf
        /// </summary>
        public AgentEventOneOf? AgentEventOneOf { get; set; }

        /// <summary>
        /// Gets or Sets AgentEventOneOf1
        /// </summary>
        public AgentEventOneOf1? AgentEventOneOf1 { get; set; }

        /// <summary>
        /// Gets or Sets AgentEventOneOf2
        /// </summary>
        public AgentEventOneOf2? AgentEventOneOf2 { get; set; }

        /// <summary>
        /// Gets or Sets AgentEventOneOf3
        /// </summary>
        public AgentEventOneOf3? AgentEventOneOf3 { get; set; }

        /// <summary>
        /// Gets or Sets AgentEventOneOf4
        /// </summary>
        public AgentEventOneOf4? AgentEventOneOf4 { get; set; }

        /// <summary>
        /// Gets or Sets AgentEventOneOf5
        /// </summary>
        public AgentEventOneOf5? AgentEventOneOf5 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentEvent {\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AgentEvent" />
    /// </summary>
    public class AgentEventJsonConverter : JsonConverter<AgentEvent>
    {
        /// <summary>
        /// Deserializes json to <see cref="AgentEvent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AgentEvent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            AgentEventOneOf? agentEventOneOf = default;
            AgentEventOneOf1? agentEventOneOf1 = default;
            AgentEventOneOf2? agentEventOneOf2 = default;
            AgentEventOneOf3? agentEventOneOf3 = default;
            AgentEventOneOf4? agentEventOneOf4 = default;
            AgentEventOneOf5? agentEventOneOf5 = default;

            Utf8JsonReader utf8JsonReaderOneOf = utf8JsonReader;
            while (utf8JsonReaderOneOf.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReaderOneOf.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReaderOneOf.CurrentDepth)
                    break;

                if (utf8JsonReaderOneOf.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReaderOneOf.CurrentDepth - 1)
                {
                    Utf8JsonReader utf8JsonReaderAgentEventOneOf = utf8JsonReader;
                    ClientUtils.TryDeserialize<AgentEventOneOf?>(ref utf8JsonReaderAgentEventOneOf, jsonSerializerOptions, out agentEventOneOf);

                    Utf8JsonReader utf8JsonReaderAgentEventOneOf1 = utf8JsonReader;
                    ClientUtils.TryDeserialize<AgentEventOneOf1?>(ref utf8JsonReaderAgentEventOneOf1, jsonSerializerOptions, out agentEventOneOf1);

                    Utf8JsonReader utf8JsonReaderAgentEventOneOf2 = utf8JsonReader;
                    ClientUtils.TryDeserialize<AgentEventOneOf2?>(ref utf8JsonReaderAgentEventOneOf2, jsonSerializerOptions, out agentEventOneOf2);

                    Utf8JsonReader utf8JsonReaderAgentEventOneOf3 = utf8JsonReader;
                    ClientUtils.TryDeserialize<AgentEventOneOf3?>(ref utf8JsonReaderAgentEventOneOf3, jsonSerializerOptions, out agentEventOneOf3);

                    Utf8JsonReader utf8JsonReaderAgentEventOneOf4 = utf8JsonReader;
                    ClientUtils.TryDeserialize<AgentEventOneOf4?>(ref utf8JsonReaderAgentEventOneOf4, jsonSerializerOptions, out agentEventOneOf4);

                    Utf8JsonReader utf8JsonReaderAgentEventOneOf5 = utf8JsonReader;
                    ClientUtils.TryDeserialize<AgentEventOneOf5?>(ref utf8JsonReaderAgentEventOneOf5, jsonSerializerOptions, out agentEventOneOf5);
                }
            }

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        default:
                            break;
                    }
                }
            }

            if (agentEventOneOf != null)
                return new AgentEvent(agentEventOneOf);

            if (agentEventOneOf1 != null)
                return new AgentEvent(agentEventOneOf1);

            if (agentEventOneOf2 != null)
                return new AgentEvent(agentEventOneOf2);

            if (agentEventOneOf3 != null)
                return new AgentEvent(agentEventOneOf3);

            if (agentEventOneOf4 != null)
                return new AgentEvent(agentEventOneOf4);

            if (agentEventOneOf5 != null)
                return new AgentEvent(agentEventOneOf5);

            throw new JsonException();
        }

        /// <summary>
        /// Serializes a <see cref="AgentEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AgentEvent agentEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, agentEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="AgentEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="agentEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, AgentEvent agentEvent, JsonSerializerOptions jsonSerializerOptions)
        {

        }
    }
}
