// <auto-generated>
/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using FirecrawlAgent.Client;

namespace FirecrawlAgent.Model
{
    /// <summary>
    /// A reusable skill package generated from the run&#39;s tool call history. Present when exportSkill&#x3D;true in the request. 
    /// </summary>
    public partial class ExportedSkill : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ExportedSkill" /> class.
        /// </summary>
        /// <param name="name">Slug identifier for the skill.</param>
        /// <param name="skillMd">Full SKILL.md content with frontmatter.</param>
        /// <param name="workflow">Deterministic workflow.mjs script content.</param>
        /// <param name="schema">Expected output schema.json content.</param>
        [JsonConstructor]
        public ExportedSkill(Option<string?> name = default, Option<string?> skillMd = default, Option<string?> workflow = default, Option<string?> schema = default)
        {
            NameOption = name;
            SkillMdOption = skillMd;
            WorkflowOption = workflow;
            SchemaOption = schema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Slug identifier for the skill.
        /// </summary>
        /// <value>Slug identifier for the skill.</value>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of SkillMd
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SkillMdOption { get; private set; }

        /// <summary>
        /// Full SKILL.md content with frontmatter.
        /// </summary>
        /// <value>Full SKILL.md content with frontmatter.</value>
        [JsonPropertyName("skillMd")]
        public string? SkillMd { get { return this.SkillMdOption; } set { this.SkillMdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Workflow
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> WorkflowOption { get; private set; }

        /// <summary>
        /// Deterministic workflow.mjs script content.
        /// </summary>
        /// <value>Deterministic workflow.mjs script content.</value>
        [JsonPropertyName("workflow")]
        public string? Workflow { get { return this.WorkflowOption; } set { this.WorkflowOption = new(value); } }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SchemaOption { get; private set; }

        /// <summary>
        /// Expected output schema.json content.
        /// </summary>
        /// <value>Expected output schema.json content.</value>
        [JsonPropertyName("schema")]
        public string? Schema { get { return this.SchemaOption; } set { this.SchemaOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExportedSkill {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  SkillMd: ").Append(SkillMd).Append("\n");
            sb.Append("  Workflow: ").Append(Workflow).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ExportedSkill" />
    /// </summary>
    public class ExportedSkillJsonConverter : JsonConverter<ExportedSkill>
    {
        /// <summary>
        /// Deserializes json to <see cref="ExportedSkill" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ExportedSkill Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> skillMd = default;
            Option<string?> workflow = default;
            Option<string?> schema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "skillMd":
                            skillMd = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "workflow":
                            workflow = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "schema":
                            schema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ExportedSkill.");

            if (skillMd.IsSet && skillMd.Value == null)
                throw new ArgumentNullException(nameof(skillMd), "Property is not nullable for class ExportedSkill.");

            if (workflow.IsSet && workflow.Value == null)
                throw new ArgumentNullException(nameof(workflow), "Property is not nullable for class ExportedSkill.");

            if (schema.IsSet && schema.Value == null)
                throw new ArgumentNullException(nameof(schema), "Property is not nullable for class ExportedSkill.");

            return new ExportedSkill(name, skillMd, workflow, schema);
        }

        /// <summary>
        /// Serializes a <see cref="ExportedSkill" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="exportedSkill"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ExportedSkill exportedSkill, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, exportedSkill, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ExportedSkill" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="exportedSkill"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ExportedSkill exportedSkill, JsonSerializerOptions jsonSerializerOptions)
        {
            if (exportedSkill.NameOption.IsSet && exportedSkill.Name == null)
                throw new ArgumentNullException(nameof(exportedSkill.Name), "Property is required for class ExportedSkill.");

            if (exportedSkill.SkillMdOption.IsSet && exportedSkill.SkillMd == null)
                throw new ArgumentNullException(nameof(exportedSkill.SkillMd), "Property is required for class ExportedSkill.");

            if (exportedSkill.WorkflowOption.IsSet && exportedSkill.Workflow == null)
                throw new ArgumentNullException(nameof(exportedSkill.Workflow), "Property is required for class ExportedSkill.");

            if (exportedSkill.SchemaOption.IsSet && exportedSkill.Schema == null)
                throw new ArgumentNullException(nameof(exportedSkill.Schema), "Property is required for class ExportedSkill.");

            if (exportedSkill.NameOption.IsSet)
                writer.WriteString("name", exportedSkill.Name);

            if (exportedSkill.SkillMdOption.IsSet)
                writer.WriteString("skillMd", exportedSkill.SkillMd);

            if (exportedSkill.WorkflowOption.IsSet)
                writer.WriteString("workflow", exportedSkill.Workflow);

            if (exportedSkill.SchemaOption.IsSet)
                writer.WriteString("schema", exportedSkill.Schema);
        }
    }
}
