/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AgentEvent_oneOf_4.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AgentEvent_oneOf_4_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AgentEvent_oneOf_4_H_

#include <boost/optional.hpp>

#include "FirecrawlAgent/ModelBase.h"

#include "FirecrawlAgent/AnyType.h"
#include "FirecrawlAgent/model/Usage.h"
#include <cpprest/details/basic_types.h>
#include "FirecrawlAgent/model/StepDetail.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class StepDetail;
class Usage;


class  AgentEvent_oneOf_4
    : public ModelBase
{
public:
    AgentEvent_oneOf_4();
    virtual ~AgentEvent_oneOf_4();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// AgentEvent_oneOf_4 members


    std::shared_ptr<AnyType> getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(const std::shared_ptr<AnyType>& value);

    utility::string_t getText() const;
    bool textIsSet() const;
    void unsetText();
    void setText(const utility::string_t& value);

    std::vector<std::shared_ptr<StepDetail>> getSteps() const;
    bool stepsIsSet() const;
    void unsetSteps();
    void setSteps(const std::vector<std::shared_ptr<StepDetail>>& value);

    std::shared_ptr<Usage> getUsage() const;
    bool usageIsSet() const;
    void unsetUsage();
    void setUsage(const std::shared_ptr<Usage>& value);


protected:
    boost::optional<std::shared_ptr<AnyType>> m_Type;

    utility::string_t m_Text;
    bool m_TextIsSet;

    std::vector<std::shared_ptr<StepDetail>> m_Steps;
    bool m_StepsIsSet;

    std::shared_ptr<Usage> m_Usage;
    bool m_UsageIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AgentEvent_oneOf_4_H_ */
