/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AgentEvent.h
 *
 * Server-sent event payload (when stream&#x3D;true)
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AgentEvent_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AgentEvent_H_

#include <variant>
#include <boost/optional.hpp>

#include "FirecrawlAgent/ModelBase.h"

#include "FirecrawlAgent/AnyType.h"
#include "FirecrawlAgent/model/Usage.h"
#include "FirecrawlAgent/model/AgentEvent_oneOf_1.h"
#include "FirecrawlAgent/model/AgentEvent_oneOf_2.h"
#include "FirecrawlAgent/model/AgentEvent_oneOf.h"
#include "FirecrawlAgent/Object.h"
#include <cpprest/details/basic_types.h>
#include "FirecrawlAgent/model/AgentEvent_oneOf_3.h"
#include "FirecrawlAgent/model/AgentEvent_oneOf_4.h"
#include "FirecrawlAgent/model/AgentEvent_oneOf_5.h"
#include "FirecrawlAgent/model/StepDetail.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Usage;
class StepDetail;


class  AgentEvent
{
public:
    AgentEvent() = default;
    ~AgentEvent() = default;

    /////////////////////////////////////////////

    void validate();

    web::json::value toJson() const;

    template<typename Target>
    bool fromJson(const web::json::value& json) {
        // convert json to Target type
        Target target;
        if (!target.fromJson(json)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const;

    template<typename Target>
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) {
        // convert multipart to Target type
        Target target;
        if (!target.fromMultiPart(multipart, namePrefix)) {
            return false;
        }

        m_variantValue = target;
        return true;
    }

    /////////////////////////////////////////////
    /// AgentEvent members

    using VariantType = std::variant<AgentEvent_oneOf, AgentEvent_oneOf_1, AgentEvent_oneOf_2, AgentEvent_oneOf_3, AgentEvent_oneOf_4, AgentEvent_oneOf_5>;

    const VariantType& getVariant() const;
    void setVariant(VariantType value);

protected:
    VariantType m_variantValue;
};



}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AgentEvent_H_ */
