/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ExportedSkill.h
 *
 * A reusable skill package generated from the run&#39;s tool call history. Present when exportSkill&#x3D;true in the request. 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_ExportedSkill_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_ExportedSkill_H_

#include <boost/optional.hpp>

#include "FirecrawlAgent/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// A reusable skill package generated from the run&#39;s tool call history. Present when exportSkill&#x3D;true in the request. 
/// </summary>
class  ExportedSkill
    : public ModelBase
{
public:
    ExportedSkill();
    virtual ~ExportedSkill();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// ExportedSkill members


    /// <summary>
    /// Slug identifier for the skill.
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();
    void setName(const utility::string_t& value);

    /// <summary>
    /// Full SKILL.md content with frontmatter.
    /// </summary>
    utility::string_t getSkillMd() const;
    bool skillMdIsSet() const;
    void unsetSkillMd();
    void setSkillMd(const utility::string_t& value);

    /// <summary>
    /// Deterministic workflow.mjs script content.
    /// </summary>
    utility::string_t getWorkflow() const;
    bool workflowIsSet() const;
    void unsetWorkflow();
    void setWorkflow(const utility::string_t& value);

    /// <summary>
    /// Expected output schema.json content.
    /// </summary>
    utility::string_t getSchema() const;
    bool schemaIsSet() const;
    void unsetSchema();
    void setSchema(const utility::string_t& value);


protected:
    utility::string_t m_Name;
    bool m_NameIsSet;

    utility::string_t m_SkillMd;
    bool m_SkillMdIsSet;

    utility::string_t m_Workflow;
    bool m_WorkflowIsSet;

    utility::string_t m_Schema;
    bool m_SchemaIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_ExportedSkill_H_ */
