/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RunRequest.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_RunRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_RunRequest_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "FirecrawlAgent/ModelBase.h"

#include "FirecrawlAgent/model/ModelConfig.h"
#include "FirecrawlAgent/Object.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class ModelConfig;


class  RunRequest
    : public ModelBase
{
public:
    RunRequest();
    virtual ~RunRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// RunRequest members

    enum class FormatEnum
    {
        JSON,
        CSV,
        MARKDOWN,
    };
    /// <summary>
    /// Desired output format. If set, agent will format data accordingly.
    /// </summary>

    FormatEnum toFormatEnum(const utility::string_t& value) const;
    const utility::string_t fromFormatEnum(const FormatEnum value) const;


    /// <summary>
    /// The research task or question.
    /// </summary>
    utility::string_t getPrompt() const;
    bool promptIsSet() const;
    void unsetPrompt();
    void setPrompt(const utility::string_t& value);

    /// <summary>
    /// If true, response is an SSE stream of AgentEvent objects.
    /// </summary>
    bool isStream() const;
    bool streamIsSet() const;
    void unsetStream();
    void setStream(bool value);

    /// <summary>
    /// Desired output format. If set, agent will format data accordingly.
    /// </summary>
    FormatEnum getFormat() const;
    bool formatIsSet() const;
    void unsetFormat();
    void setFormat(const FormatEnum value);

    /// <summary>
    /// JSON Schema for structured output (used with format&#x3D;json).
    /// </summary>
    std::shared_ptr<Object> getSchema() const;
    bool schemaIsSet() const;
    void unsetSchema();
    void setSchema(const std::shared_ptr<Object>& value);

    /// <summary>
    /// Column names for CSV output.
    /// </summary>
    std::vector<utility::string_t> getColumns() const;
    bool columnsIsSet() const;
    void unsetColumns();
    void setColumns(const std::vector<utility::string_t>& value);

    /// <summary>
    /// Seed URLs to start from instead of searching.
    /// </summary>
    std::vector<utility::string_t> getUrls() const;
    bool urlsIsSet() const;
    void unsetUrls();
    void setUrls(const std::vector<utility::string_t>& value);

    std::shared_ptr<ModelConfig> getModel() const;
    bool modelIsSet() const;
    void unsetModel();
    void setModel(const std::shared_ptr<ModelConfig>& value);

    std::shared_ptr<ModelConfig> getSubAgentModel() const;
    bool subAgentModelIsSet() const;
    void unsetSubAgentModel();
    void setSubAgentModel(const std::shared_ptr<ModelConfig>& value);

    /// <summary>
    /// Maximum agent steps before stopping.
    /// </summary>
    int32_t getMaxSteps() const;
    bool maxStepsIsSet() const;
    void unsetMaxSteps();
    void setMaxSteps(int32_t value);

    /// <summary>
    /// Skills to pre-load for this run.
    /// </summary>
    std::vector<utility::string_t> getSkills() const;
    bool skillsIsSet() const;
    void unsetSkills();
    void setSkills(const std::vector<utility::string_t>& value);


protected:
    utility::string_t m_Prompt;
    bool m_PromptIsSet;

    bool m_Stream;
    bool m_StreamIsSet;

    FormatEnum m_Format;
    bool m_FormatIsSet;

    std::shared_ptr<Object> m_Schema;
    bool m_SchemaIsSet;

    std::vector<utility::string_t> m_Columns;
    bool m_ColumnsIsSet;

    std::vector<utility::string_t> m_Urls;
    bool m_UrlsIsSet;

    std::shared_ptr<ModelConfig> m_Model;
    bool m_ModelIsSet;

    std::shared_ptr<ModelConfig> m_SubAgentModel;
    bool m_SubAgentModelIsSet;

    int32_t m_MaxSteps;
    bool m_MaxStepsIsSet;

    std::vector<utility::string_t> m_Skills;
    bool m_SkillsIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_RunRequest_H_ */
