/**
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.21.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WorkerProgress.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_WorkerProgress_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_WorkerProgress_H_

#include <stdexcept>
#include <boost/optional.hpp>

#include "FirecrawlAgent/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "FirecrawlAgent/model/WorkerProgress_stepLog_inner.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class WorkerProgress_stepLog_inner;


class  WorkerProgress
    : public ModelBase
{
public:
    WorkerProgress();
    virtual ~WorkerProgress();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;


    /////////////////////////////////////////////
    /// WorkerProgress members

    enum class StatusEnum
    {
        RUNNING,
        DONE,
        ERROR,
    };

    StatusEnum toStatusEnum(const utility::string_t& value) const;
    const utility::string_t fromStatusEnum(const StatusEnum value) const;


    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();
    void setId(const utility::string_t& value);

    StatusEnum getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();
    void setStatus(const StatusEnum value);

    int32_t getSteps() const;
    bool stepsIsSet() const;
    void unsetSteps();
    void setSteps(int32_t value);

    utility::string_t getCurrentTool() const;
    bool currentToolIsSet() const;
    void unsetCurrentTool();
    void setCurrentTool(const utility::string_t& value);

    int32_t getTokens() const;
    bool tokensIsSet() const;
    void unsetTokens();
    void setTokens(int32_t value);

    std::vector<std::shared_ptr<WorkerProgress_stepLog_inner>> getStepLog() const;
    bool stepLogIsSet() const;
    void unsetStepLog();
    void setStepLog(const std::vector<std::shared_ptr<WorkerProgress_stepLog_inner>>& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;

    StatusEnum m_Status;
    bool m_StatusIsSet;

    int32_t m_Steps;
    bool m_StepsIsSet;

    utility::string_t m_CurrentTool;
    bool m_CurrentToolIsSet;

    int32_t m_Tokens;
    bool m_TokensIsSet;

    std::vector<std::shared_ptr<WorkerProgress_stepLog_inner>> m_StepLog;
    bool m_StepLogIsSet;

};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_WorkerProgress_H_ */
