/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FirecrawlAgent.Model;
using FirecrawlAgent.Client;
using System.Reflection;

namespace FirecrawlAgent.Test.Model
{
    /// <summary>
    ///  Class for testing AgentEventOneOf2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgentEventOneOf2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AgentEventOneOf2
        //private AgentEventOneOf2 instance;

        public AgentEventOneOf2Tests()
        {
            // TODO uncomment below to create an instance of AgentEventOneOf2
            //instance = new AgentEventOneOf2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentEventOneOf2
        /// </summary>
        [Fact]
        public void AgentEventOneOf2InstanceTest()
        {
            // TODO uncomment below to test "IsType" AgentEventOneOf2
            //Assert.IsType<AgentEventOneOf2>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Output'
        /// </summary>
        [Fact]
        public void OutputTest()
        {
            // TODO unit test for the property 'Output'
        }
    }
}
