/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using FirecrawlAgent.Model;
using FirecrawlAgent.Client;
using System.Reflection;

namespace FirecrawlAgent.Test.Model
{
    /// <summary>
    ///  Class for testing RunRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RunRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RunRequest
        //private RunRequest instance;

        public RunRequestTests()
        {
            // TODO uncomment below to create an instance of RunRequest
            //instance = new RunRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RunRequest
        /// </summary>
        [Fact]
        public void RunRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RunRequest
            //Assert.IsType<RunRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Prompt'
        /// </summary>
        [Fact]
        public void PromptTest()
        {
            // TODO unit test for the property 'Prompt'
        }

        /// <summary>
        /// Test the property 'Stream'
        /// </summary>
        [Fact]
        public void StreamTest()
        {
            // TODO unit test for the property 'Stream'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'Columns'
        /// </summary>
        [Fact]
        public void ColumnsTest()
        {
            // TODO unit test for the property 'Columns'
        }

        /// <summary>
        /// Test the property 'Urls'
        /// </summary>
        [Fact]
        public void UrlsTest()
        {
            // TODO unit test for the property 'Urls'
        }

        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

        /// <summary>
        /// Test the property 'SubAgentModel'
        /// </summary>
        [Fact]
        public void SubAgentModelTest()
        {
            // TODO unit test for the property 'SubAgentModel'
        }

        /// <summary>
        /// Test the property 'MaxSteps'
        /// </summary>
        [Fact]
        public void MaxStepsTest()
        {
            // TODO unit test for the property 'MaxSteps'
        }

        /// <summary>
        /// Test the property 'Skills'
        /// </summary>
        [Fact]
        public void SkillsTest()
        {
            // TODO unit test for the property 'Skills'
        }
    }
}
