// <auto-generated>
/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using FirecrawlAgent.Client;

namespace FirecrawlAgent.Model
{
    /// <summary>
    /// RunResponse
    /// </summary>
    public partial class RunResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RunResponse" /> class.
        /// </summary>
        /// <param name="text">The agent&#39;s final text response.</param>
        /// <param name="data">Formatted output (present when format was specified).</param>
        /// <param name="format">The format of the data field.</param>
        /// <param name="steps">steps</param>
        /// <param name="usage">usage</param>
        [JsonConstructor]
        public RunResponse(Option<string?> text = default, Option<string?> data = default, Option<FormatEnum?> format = default, Option<List<StepDetail>?> steps = default, Option<Usage?> usage = default)
        {
            TextOption = text;
            DataOption = data;
            FormatOption = format;
            StepsOption = steps;
            UsageOption = usage;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// The format of the data field.
        /// </summary>
        /// <value>The format of the data field.</value>
        public enum FormatEnum
        {
            /// <summary>
            /// Enum Json for value: json
            /// </summary>
            Json = 1,

            /// <summary>
            /// Enum Csv for value: csv
            /// </summary>
            Csv = 2,

            /// <summary>
            /// Enum Markdown for value: markdown
            /// </summary>
            Markdown = 3,

            /// <summary>
            /// Enum Text for value: text
            /// </summary>
            Text = 4
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static FormatEnum FormatEnumFromString(string value)
        {
            if (value.Equals("json"))
                return FormatEnum.Json;

            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("markdown"))
                return FormatEnum.Markdown;

            if (value.Equals("text"))
                return FormatEnum.Text;

            throw new NotImplementedException($"Could not convert value to type FormatEnum: '{value}'");
        }

        /// <summary>
        /// Returns a <see cref="FormatEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static FormatEnum? FormatEnumFromStringOrDefault(string value)
        {
            if (value.Equals("json"))
                return FormatEnum.Json;

            if (value.Equals("csv"))
                return FormatEnum.Csv;

            if (value.Equals("markdown"))
                return FormatEnum.Markdown;

            if (value.Equals("text"))
                return FormatEnum.Text;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="FormatEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string FormatEnumToJsonValue(FormatEnum? value)
        {
            if (value == FormatEnum.Json)
                return "json";

            if (value == FormatEnum.Csv)
                return "csv";

            if (value == FormatEnum.Markdown)
                return "markdown";

            if (value == FormatEnum.Text)
                return "text";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }

        /// <summary>
        /// Used to track the state of Format
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<FormatEnum?> FormatOption { get; private set; }

        /// <summary>
        /// The format of the data field.
        /// </summary>
        /// <value>The format of the data field.</value>
        [JsonPropertyName("format")]
        public FormatEnum? Format { get { return this.FormatOption.Value; } set { this.FormatOption = new(value); } }

        /// <summary>
        /// Used to track the state of Text
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TextOption { get; private set; }

        /// <summary>
        /// The agent&#39;s final text response.
        /// </summary>
        /// <value>The agent&#39;s final text response.</value>
        [JsonPropertyName("text")]
        public string? Text { get { return this.TextOption; } set { this.TextOption = new(value); } }

        /// <summary>
        /// Used to track the state of Data
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DataOption { get; private set; }

        /// <summary>
        /// Formatted output (present when format was specified).
        /// </summary>
        /// <value>Formatted output (present when format was specified).</value>
        [JsonPropertyName("data")]
        public string? Data { get { return this.DataOption; } set { this.DataOption = new(value); } }

        /// <summary>
        /// Used to track the state of Steps
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<StepDetail>?> StepsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Steps
        /// </summary>
        [JsonPropertyName("steps")]
        public List<StepDetail>? Steps { get { return this.StepsOption; } set { this.StepsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Usage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Usage?> UsageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Usage
        /// </summary>
        [JsonPropertyName("usage")]
        public Usage? Usage { get { return this.UsageOption; } set { this.UsageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RunResponse {\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Steps: ").Append(Steps).Append("\n");
            sb.Append("  Usage: ").Append(Usage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RunResponse" />
    /// </summary>
    public class RunResponseJsonConverter : JsonConverter<RunResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="RunResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RunResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> text = default;
            Option<string?> data = default;
            Option<RunResponse.FormatEnum?> format = default;
            Option<List<StepDetail>?> steps = default;
            Option<Usage?> usage = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "text":
                            text = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "data":
                            data = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "format":
                            string? formatRawValue = utf8JsonReader.GetString();
                            if (formatRawValue != null)
                                format = new Option<RunResponse.FormatEnum?>(RunResponse.FormatEnumFromStringOrDefault(formatRawValue));
                            break;
                        case "steps":
                            steps = new Option<List<StepDetail>?>(JsonSerializer.Deserialize<List<StepDetail>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "usage":
                            usage = new Option<Usage?>(JsonSerializer.Deserialize<Usage>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (text.IsSet && text.Value == null)
                throw new ArgumentNullException(nameof(text), "Property is not nullable for class RunResponse.");

            if (data.IsSet && data.Value == null)
                throw new ArgumentNullException(nameof(data), "Property is not nullable for class RunResponse.");

            if (format.IsSet && format.Value == null)
                throw new ArgumentNullException(nameof(format), "Property is not nullable for class RunResponse.");

            if (steps.IsSet && steps.Value == null)
                throw new ArgumentNullException(nameof(steps), "Property is not nullable for class RunResponse.");

            if (usage.IsSet && usage.Value == null)
                throw new ArgumentNullException(nameof(usage), "Property is not nullable for class RunResponse.");

            return new RunResponse(text, data, format, steps, usage);
        }

        /// <summary>
        /// Serializes a <see cref="RunResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="runResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RunResponse runResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, runResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RunResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="runResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RunResponse runResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (runResponse.TextOption.IsSet && runResponse.Text == null)
                throw new ArgumentNullException(nameof(runResponse.Text), "Property is required for class RunResponse.");

            if (runResponse.DataOption.IsSet && runResponse.Data == null)
                throw new ArgumentNullException(nameof(runResponse.Data), "Property is required for class RunResponse.");

            if (runResponse.StepsOption.IsSet && runResponse.Steps == null)
                throw new ArgumentNullException(nameof(runResponse.Steps), "Property is required for class RunResponse.");

            if (runResponse.UsageOption.IsSet && runResponse.Usage == null)
                throw new ArgumentNullException(nameof(runResponse.Usage), "Property is required for class RunResponse.");

            if (runResponse.TextOption.IsSet)
                writer.WriteString("text", runResponse.Text);

            if (runResponse.DataOption.IsSet)
                writer.WriteString("data", runResponse.Data);

            var formatRawValue = RunResponse.FormatEnumToJsonValue(runResponse.FormatOption.Value!.Value);
            writer.WriteString("format", formatRawValue);
            if (runResponse.StepsOption.IsSet)
            {
                writer.WritePropertyName("steps");
                JsonSerializer.Serialize(writer, runResponse.Steps, jsonSerializerOptions);
            }
            if (runResponse.UsageOption.IsSet)
            {
                writer.WritePropertyName("usage");
                JsonSerializer.Serialize(writer, runResponse.Usage, jsonSerializerOptions);
            }
        }
    }
}
