/*
Firecrawl Agent API

AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package firecrawlagent

import (
	"encoding/json"
)

// checks if the RunResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunResponse{}

// RunResponse struct for RunResponse
type RunResponse struct {
	// The agent's final text response.
	Text *string `json:"text,omitempty"`
	// Formatted output (present when format was specified).
	Data *string `json:"data,omitempty"`
	// The format of the data field.
	Format *string `json:"format,omitempty"`
	Steps []StepDetail `json:"steps,omitempty"`
	Usage *Usage `json:"usage,omitempty"`
	ExportedSkill *ExportedSkill `json:"exportedSkill,omitempty"`
}

// NewRunResponse instantiates a new RunResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunResponse() *RunResponse {
	this := RunResponse{}
	return &this
}

// NewRunResponseWithDefaults instantiates a new RunResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunResponseWithDefaults() *RunResponse {
	this := RunResponse{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RunResponse) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunResponse) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RunResponse) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RunResponse) SetText(v string) {
	o.Text = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RunResponse) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunResponse) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RunResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *RunResponse) SetData(v string) {
	o.Data = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *RunResponse) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunResponse) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *RunResponse) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *RunResponse) SetFormat(v string) {
	o.Format = &v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *RunResponse) GetSteps() []StepDetail {
	if o == nil || IsNil(o.Steps) {
		var ret []StepDetail
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunResponse) GetStepsOk() ([]StepDetail, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *RunResponse) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []StepDetail and assigns it to the Steps field.
func (o *RunResponse) SetSteps(v []StepDetail) {
	o.Steps = v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *RunResponse) GetUsage() Usage {
	if o == nil || IsNil(o.Usage) {
		var ret Usage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunResponse) GetUsageOk() (*Usage, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *RunResponse) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given Usage and assigns it to the Usage field.
func (o *RunResponse) SetUsage(v Usage) {
	o.Usage = &v
}

// GetExportedSkill returns the ExportedSkill field value if set, zero value otherwise.
func (o *RunResponse) GetExportedSkill() ExportedSkill {
	if o == nil || IsNil(o.ExportedSkill) {
		var ret ExportedSkill
		return ret
	}
	return *o.ExportedSkill
}

// GetExportedSkillOk returns a tuple with the ExportedSkill field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunResponse) GetExportedSkillOk() (*ExportedSkill, bool) {
	if o == nil || IsNil(o.ExportedSkill) {
		return nil, false
	}
	return o.ExportedSkill, true
}

// HasExportedSkill returns a boolean if a field has been set.
func (o *RunResponse) HasExportedSkill() bool {
	if o != nil && !IsNil(o.ExportedSkill) {
		return true
	}

	return false
}

// SetExportedSkill gets a reference to the given ExportedSkill and assigns it to the ExportedSkill field.
func (o *RunResponse) SetExportedSkill(v ExportedSkill) {
	o.ExportedSkill = &v
}

func (o RunResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	if !IsNil(o.ExportedSkill) {
		toSerialize["exportedSkill"] = o.ExportedSkill
	}
	return toSerialize, nil
}

type NullableRunResponse struct {
	value *RunResponse
	isSet bool
}

func (v NullableRunResponse) Get() *RunResponse {
	return v.value
}

func (v *NullableRunResponse) Set(val *RunResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRunResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRunResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunResponse(val *RunResponse) *NullableRunResponse {
	return &NullableRunResponse{value: val, isSet: true}
}

func (v NullableRunResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


