#
# Firecrawl Agent API
# AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
# Version: 0.1.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Prompt
The research task or question.
.PARAMETER Stream
If true, response is an SSE stream of AgentEvent objects.
.PARAMETER Format
Desired output format. If set, agent will format data accordingly.
.PARAMETER Schema
JSON schema that serves as both a research plan and output format. The agent treats each field as a data point to collect during research. Array fields mean ""find all items."" The final output is compiled into this exact shape. Used with format=json. 
.PARAMETER Columns
Column names for CSV output. Each column acts as a required data point the agent will research. The final CSV contains one column per entry. 
.PARAMETER Urls
Seed URLs to start from instead of searching.
.PARAMETER Model
No description available.
.PARAMETER SubAgentModel
No description available.
.PARAMETER MaxSteps
Maximum agent steps before stopping.
.PARAMETER Skills
Skills to pre-load for this run.
.OUTPUTS

RunRequest<PSCustomObject>
#>

function Initialize-RunRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Prompt},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Stream} = $false,
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("json", "csv", "markdown")]
        [String]
        ${Format},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Schema},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Columns},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Urls},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Model},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SubAgentModel},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MaxSteps} = 15,
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Skills}
    )

    Process {
        'Creating PSCustomObject: FirecrawlAgent => RunRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Prompt) {
            throw "invalid value for 'Prompt', 'Prompt' cannot be null."
        }

        if ($MaxSteps -and $MaxSteps -gt 50) {
          throw "invalid value for 'MaxSteps', must be smaller than or equal to 50."
        }

        if ($MaxSteps -and $MaxSteps -lt 1) {
          throw "invalid value for 'MaxSteps', must be greater than or equal to 1."
        }


        $PSO = [PSCustomObject]@{
            "prompt" = ${Prompt}
            "stream" = ${Stream}
            "format" = ${Format}
            "schema" = ${Schema}
            "columns" = ${Columns}
            "urls" = ${Urls}
            "model" = ${Model}
            "subAgentModel" = ${SubAgentModel}
            "maxSteps" = ${MaxSteps}
            "skills" = ${Skills}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RunRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to RunRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RunRequest<PSCustomObject>
#>
function ConvertFrom-JsonToRunRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: FirecrawlAgent => RunRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RunRequest
        $AllProperties = ("prompt", "stream", "format", "schema", "columns", "urls", "model", "subAgentModel", "maxSteps", "skills")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'prompt' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "prompt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'prompt' missing."
        } else {
            $Prompt = $JsonParameters.PSobject.Properties["prompt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "stream"))) { #optional property not found
            $Stream = $null
        } else {
            $Stream = $JsonParameters.PSobject.Properties["stream"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "format"))) { #optional property not found
            $Format = $null
        } else {
            $Format = $JsonParameters.PSobject.Properties["format"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "schema"))) { #optional property not found
            $Schema = $null
        } else {
            $Schema = $JsonParameters.PSobject.Properties["schema"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "columns"))) { #optional property not found
            $Columns = $null
        } else {
            $Columns = $JsonParameters.PSobject.Properties["columns"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "urls"))) { #optional property not found
            $Urls = $null
        } else {
            $Urls = $JsonParameters.PSobject.Properties["urls"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "model"))) { #optional property not found
            $Model = $null
        } else {
            $Model = $JsonParameters.PSobject.Properties["model"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "subAgentModel"))) { #optional property not found
            $SubAgentModel = $null
        } else {
            $SubAgentModel = $JsonParameters.PSobject.Properties["subAgentModel"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxSteps"))) { #optional property not found
            $MaxSteps = $null
        } else {
            $MaxSteps = $JsonParameters.PSobject.Properties["maxSteps"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "skills"))) { #optional property not found
            $Skills = $null
        } else {
            $Skills = $JsonParameters.PSobject.Properties["skills"].value
        }

        $PSO = [PSCustomObject]@{
            "prompt" = ${Prompt}
            "stream" = ${Stream}
            "format" = ${Format}
            "schema" = ${Schema}
            "columns" = ${Columns}
            "urls" = ${Urls}
            "model" = ${Model}
            "subAgentModel" = ${SubAgentModel}
            "maxSteps" = ${MaxSteps}
            "skills" = ${Skills}
        }

        return $PSO
    }

}

