/*
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firecrawl.agent.model;

import java.util.Objects;
import com.firecrawl.agent.model.ModelConfig;
import com.firecrawl.agent.model.SubAgentConfig;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.firecrawl.agent.JSON;

/**
 * RunRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-06T10:50:08.867642-04:00[America/Toronto]", comments = "Generator version: 7.21.0")
public class RunRequest {
  public static final String SERIALIZED_NAME_PROMPT = "prompt";
  @SerializedName(SERIALIZED_NAME_PROMPT)
  @javax.annotation.Nonnull
  private String prompt;

  public static final String SERIALIZED_NAME_STREAM = "stream";
  @SerializedName(SERIALIZED_NAME_STREAM)
  @javax.annotation.Nullable
  private Boolean stream = false;

  /**
   * Desired output format. If set, agent will format data accordingly.
   */
  @JsonAdapter(FormatEnum.Adapter.class)
  public enum FormatEnum {
    JSON("json"),
    
    CSV("csv"),
    
    MARKDOWN("markdown");

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FormatEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FormatEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FormatEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FormatEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      FormatEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  @javax.annotation.Nullable
  private FormatEnum format;

  public static final String SERIALIZED_NAME_SCHEMA = "schema";
  @SerializedName(SERIALIZED_NAME_SCHEMA)
  @javax.annotation.Nullable
  private Object schema;

  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  @javax.annotation.Nullable
  private List<String> columns = new ArrayList<>();

  public static final String SERIALIZED_NAME_URLS = "urls";
  @SerializedName(SERIALIZED_NAME_URLS)
  @javax.annotation.Nullable
  private List<String> urls = new ArrayList<>();

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nullable
  private ModelConfig model;

  public static final String SERIALIZED_NAME_SUB_AGENT_MODEL = "subAgentModel";
  @SerializedName(SERIALIZED_NAME_SUB_AGENT_MODEL)
  @javax.annotation.Nullable
  private ModelConfig subAgentModel;

  public static final String SERIALIZED_NAME_MAX_STEPS = "maxSteps";
  @SerializedName(SERIALIZED_NAME_MAX_STEPS)
  @javax.annotation.Nullable
  private Integer maxSteps = 15;

  public static final String SERIALIZED_NAME_SKILLS = "skills";
  @SerializedName(SERIALIZED_NAME_SKILLS)
  @javax.annotation.Nullable
  private List<String> skills = new ArrayList<>();

  public static final String SERIALIZED_NAME_SKILL_INSTRUCTIONS = "skillInstructions";
  @SerializedName(SERIALIZED_NAME_SKILL_INSTRUCTIONS)
  @javax.annotation.Nullable
  private Map<String, String> skillInstructions = new HashMap<>();

  public static final String SERIALIZED_NAME_SUB_AGENTS = "subAgents";
  @SerializedName(SERIALIZED_NAME_SUB_AGENTS)
  @javax.annotation.Nullable
  private List<SubAgentConfig> subAgents = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPORT_SKILL = "exportSkill";
  @SerializedName(SERIALIZED_NAME_EXPORT_SKILL)
  @javax.annotation.Nullable
  private Boolean exportSkill = false;

  public RunRequest() {
  }

  public RunRequest prompt(@javax.annotation.Nonnull String prompt) {
    this.prompt = prompt;
    return this;
  }

  /**
   * The research task or question.
   * @return prompt
   */
  @javax.annotation.Nonnull
  public String getPrompt() {
    return prompt;
  }

  public void setPrompt(@javax.annotation.Nonnull String prompt) {
    this.prompt = prompt;
  }


  public RunRequest stream(@javax.annotation.Nullable Boolean stream) {
    this.stream = stream;
    return this;
  }

  /**
   * If true, response is an SSE stream of AgentEvent objects.
   * @return stream
   */
  @javax.annotation.Nullable
  public Boolean getStream() {
    return stream;
  }

  public void setStream(@javax.annotation.Nullable Boolean stream) {
    this.stream = stream;
  }


  public RunRequest format(@javax.annotation.Nullable FormatEnum format) {
    this.format = format;
    return this;
  }

  /**
   * Desired output format. If set, agent will format data accordingly.
   * @return format
   */
  @javax.annotation.Nullable
  public FormatEnum getFormat() {
    return format;
  }

  public void setFormat(@javax.annotation.Nullable FormatEnum format) {
    this.format = format;
  }


  public RunRequest schema(@javax.annotation.Nullable Object schema) {
    this.schema = schema;
    return this;
  }

  /**
   * JSON schema that serves as both a research plan and output format. The agent treats each field as a data point to collect during research. Array fields mean \&quot;find all items.\&quot; The final output is compiled into this exact shape. Used with format&#x3D;json. 
   * @return schema
   */
  @javax.annotation.Nullable
  public Object getSchema() {
    return schema;
  }

  public void setSchema(@javax.annotation.Nullable Object schema) {
    this.schema = schema;
  }


  public RunRequest columns(@javax.annotation.Nullable List<String> columns) {
    this.columns = columns;
    return this;
  }

  public RunRequest addColumnsItem(String columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Column names for CSV output. Each column acts as a required data point the agent will research. The final CSV contains one column per entry. 
   * @return columns
   */
  @javax.annotation.Nullable
  public List<String> getColumns() {
    return columns;
  }

  public void setColumns(@javax.annotation.Nullable List<String> columns) {
    this.columns = columns;
  }


  public RunRequest urls(@javax.annotation.Nullable List<String> urls) {
    this.urls = urls;
    return this;
  }

  public RunRequest addUrlsItem(String urlsItem) {
    if (this.urls == null) {
      this.urls = new ArrayList<>();
    }
    this.urls.add(urlsItem);
    return this;
  }

  /**
   * Seed URLs to start from instead of searching.
   * @return urls
   */
  @javax.annotation.Nullable
  public List<String> getUrls() {
    return urls;
  }

  public void setUrls(@javax.annotation.Nullable List<String> urls) {
    this.urls = urls;
  }


  public RunRequest model(@javax.annotation.Nullable ModelConfig model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  public ModelConfig getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nullable ModelConfig model) {
    this.model = model;
  }


  public RunRequest subAgentModel(@javax.annotation.Nullable ModelConfig subAgentModel) {
    this.subAgentModel = subAgentModel;
    return this;
  }

  /**
   * Get subAgentModel
   * @return subAgentModel
   */
  @javax.annotation.Nullable
  public ModelConfig getSubAgentModel() {
    return subAgentModel;
  }

  public void setSubAgentModel(@javax.annotation.Nullable ModelConfig subAgentModel) {
    this.subAgentModel = subAgentModel;
  }


  public RunRequest maxSteps(@javax.annotation.Nullable Integer maxSteps) {
    this.maxSteps = maxSteps;
    return this;
  }

  /**
   * Maximum agent steps before stopping.
   * minimum: 1
   * maximum: 50
   * @return maxSteps
   */
  @javax.annotation.Nullable
  public Integer getMaxSteps() {
    return maxSteps;
  }

  public void setMaxSteps(@javax.annotation.Nullable Integer maxSteps) {
    this.maxSteps = maxSteps;
  }


  public RunRequest skills(@javax.annotation.Nullable List<String> skills) {
    this.skills = skills;
    return this;
  }

  public RunRequest addSkillsItem(String skillsItem) {
    if (this.skills == null) {
      this.skills = new ArrayList<>();
    }
    this.skills.add(skillsItem);
    return this;
  }

  /**
   * Skills to pre-load for this run.
   * @return skills
   */
  @javax.annotation.Nullable
  public List<String> getSkills() {
    return skills;
  }

  public void setSkills(@javax.annotation.Nullable List<String> skills) {
    this.skills = skills;
  }


  public RunRequest skillInstructions(@javax.annotation.Nullable Map<String, String> skillInstructions) {
    this.skillInstructions = skillInstructions;
    return this;
  }

  public RunRequest putSkillInstructionsItem(String key, String skillInstructionsItem) {
    if (this.skillInstructions == null) {
      this.skillInstructions = new HashMap<>();
    }
    this.skillInstructions.put(key, skillInstructionsItem);
    return this;
  }

  /**
   * Per-skill custom instructions. Keys are skill names, values are instruction strings appended when the skill is loaded. 
   * @return skillInstructions
   */
  @javax.annotation.Nullable
  public Map<String, String> getSkillInstructions() {
    return skillInstructions;
  }

  public void setSkillInstructions(@javax.annotation.Nullable Map<String, String> skillInstructions) {
    this.skillInstructions = skillInstructions;
  }


  public RunRequest subAgents(@javax.annotation.Nullable List<SubAgentConfig> subAgents) {
    this.subAgents = subAgents;
    return this;
  }

  public RunRequest addSubAgentsItem(SubAgentConfig subAgentsItem) {
    if (this.subAgents == null) {
      this.subAgents = new ArrayList<>();
    }
    this.subAgents.add(subAgentsItem);
    return this;
  }

  /**
   * Sub-agents available during this run. Each sub-agent becomes a tool the orchestrator can delegate tasks to. 
   * @return subAgents
   */
  @javax.annotation.Nullable
  public List<SubAgentConfig> getSubAgents() {
    return subAgents;
  }

  public void setSubAgents(@javax.annotation.Nullable List<SubAgentConfig> subAgents) {
    this.subAgents = subAgents;
  }


  public RunRequest exportSkill(@javax.annotation.Nullable Boolean exportSkill) {
    this.exportSkill = exportSkill;
    return this;
  }

  /**
   * When true, post-processes the run into a reusable skill package (SKILL.md + workflow.mjs + schema.json) returned in the response. 
   * @return exportSkill
   */
  @javax.annotation.Nullable
  public Boolean getExportSkill() {
    return exportSkill;
  }

  public void setExportSkill(@javax.annotation.Nullable Boolean exportSkill) {
    this.exportSkill = exportSkill;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RunRequest runRequest = (RunRequest) o;
    return Objects.equals(this.prompt, runRequest.prompt) &&
        Objects.equals(this.stream, runRequest.stream) &&
        Objects.equals(this.format, runRequest.format) &&
        Objects.equals(this.schema, runRequest.schema) &&
        Objects.equals(this.columns, runRequest.columns) &&
        Objects.equals(this.urls, runRequest.urls) &&
        Objects.equals(this.model, runRequest.model) &&
        Objects.equals(this.subAgentModel, runRequest.subAgentModel) &&
        Objects.equals(this.maxSteps, runRequest.maxSteps) &&
        Objects.equals(this.skills, runRequest.skills) &&
        Objects.equals(this.skillInstructions, runRequest.skillInstructions) &&
        Objects.equals(this.subAgents, runRequest.subAgents) &&
        Objects.equals(this.exportSkill, runRequest.exportSkill);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompt, stream, format, schema, columns, urls, model, subAgentModel, maxSteps, skills, skillInstructions, subAgents, exportSkill);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RunRequest {\n");
    sb.append("    prompt: ").append(toIndentedString(prompt)).append("\n");
    sb.append("    stream: ").append(toIndentedString(stream)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    subAgentModel: ").append(toIndentedString(subAgentModel)).append("\n");
    sb.append("    maxSteps: ").append(toIndentedString(maxSteps)).append("\n");
    sb.append("    skills: ").append(toIndentedString(skills)).append("\n");
    sb.append("    skillInstructions: ").append(toIndentedString(skillInstructions)).append("\n");
    sb.append("    subAgents: ").append(toIndentedString(subAgents)).append("\n");
    sb.append("    exportSkill: ").append(toIndentedString(exportSkill)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("prompt", "stream", "format", "schema", "columns", "urls", "model", "subAgentModel", "maxSteps", "skills", "skillInstructions", "subAgents", "exportSkill"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("prompt"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RunRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RunRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RunRequest is not found in the empty JSON string", RunRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RunRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RunRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RunRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("prompt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `prompt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prompt").toString()));
      }
      if ((jsonObj.get("format") != null && !jsonObj.get("format").isJsonNull()) && !jsonObj.get("format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("format").toString()));
      }
      // validate the optional field `format`
      if (jsonObj.get("format") != null && !jsonObj.get("format").isJsonNull()) {
        FormatEnum.validateJsonElement(jsonObj.get("format"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("columns") != null && !jsonObj.get("columns").isJsonNull() && !jsonObj.get("columns").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `columns` to be an array in the JSON string but got `%s`", jsonObj.get("columns").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("urls") != null && !jsonObj.get("urls").isJsonNull() && !jsonObj.get("urls").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `urls` to be an array in the JSON string but got `%s`", jsonObj.get("urls").toString()));
      }
      // validate the optional field `model`
      if (jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) {
        ModelConfig.validateJsonElement(jsonObj.get("model"));
      }
      // validate the optional field `subAgentModel`
      if (jsonObj.get("subAgentModel") != null && !jsonObj.get("subAgentModel").isJsonNull()) {
        ModelConfig.validateJsonElement(jsonObj.get("subAgentModel"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("skills") != null && !jsonObj.get("skills").isJsonNull() && !jsonObj.get("skills").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `skills` to be an array in the JSON string but got `%s`", jsonObj.get("skills").toString()));
      }
      if (jsonObj.get("subAgents") != null && !jsonObj.get("subAgents").isJsonNull()) {
        JsonArray jsonArraysubAgents = jsonObj.getAsJsonArray("subAgents");
        if (jsonArraysubAgents != null) {
          // ensure the json data is an array
          if (!jsonObj.get("subAgents").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `subAgents` to be an array in the JSON string but got `%s`", jsonObj.get("subAgents").toString()));
          }

          // validate the optional field `subAgents` (array)
          for (int i = 0; i < jsonArraysubAgents.size(); i++) {
            SubAgentConfig.validateJsonElement(jsonArraysubAgents.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RunRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RunRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RunRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RunRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<RunRequest>() {
           @Override
           public void write(JsonWriter out, RunRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RunRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RunRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RunRequest
   * @throws IOException if the JSON string is invalid with respect to RunRequest
   */
  public static RunRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RunRequest.class);
  }

  /**
   * Convert an instance of RunRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

