/*
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firecrawl.agent.model;

import java.util.Objects;
import com.firecrawl.agent.model.StepDetailToolCallsInner;
import com.firecrawl.agent.model.StepDetailToolResultsInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.firecrawl.agent.JSON;

/**
 * StepDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-31T13:14:50.457716-04:00[America/Toronto]", comments = "Generator version: 7.21.0")
public class StepDetail {
  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @javax.annotation.Nullable
  private String text;

  public static final String SERIALIZED_NAME_TOOL_CALLS = "toolCalls";
  @SerializedName(SERIALIZED_NAME_TOOL_CALLS)
  @javax.annotation.Nullable
  private List<StepDetailToolCallsInner> toolCalls = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOOL_RESULTS = "toolResults";
  @SerializedName(SERIALIZED_NAME_TOOL_RESULTS)
  @javax.annotation.Nullable
  private List<StepDetailToolResultsInner> toolResults = new ArrayList<>();

  public StepDetail() {
  }

  public StepDetail text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Get text
   * @return text
   */
  @javax.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public StepDetail toolCalls(@javax.annotation.Nullable List<StepDetailToolCallsInner> toolCalls) {
    this.toolCalls = toolCalls;
    return this;
  }

  public StepDetail addToolCallsItem(StepDetailToolCallsInner toolCallsItem) {
    if (this.toolCalls == null) {
      this.toolCalls = new ArrayList<>();
    }
    this.toolCalls.add(toolCallsItem);
    return this;
  }

  /**
   * Get toolCalls
   * @return toolCalls
   */
  @javax.annotation.Nullable
  public List<StepDetailToolCallsInner> getToolCalls() {
    return toolCalls;
  }

  public void setToolCalls(@javax.annotation.Nullable List<StepDetailToolCallsInner> toolCalls) {
    this.toolCalls = toolCalls;
  }


  public StepDetail toolResults(@javax.annotation.Nullable List<StepDetailToolResultsInner> toolResults) {
    this.toolResults = toolResults;
    return this;
  }

  public StepDetail addToolResultsItem(StepDetailToolResultsInner toolResultsItem) {
    if (this.toolResults == null) {
      this.toolResults = new ArrayList<>();
    }
    this.toolResults.add(toolResultsItem);
    return this;
  }

  /**
   * Get toolResults
   * @return toolResults
   */
  @javax.annotation.Nullable
  public List<StepDetailToolResultsInner> getToolResults() {
    return toolResults;
  }

  public void setToolResults(@javax.annotation.Nullable List<StepDetailToolResultsInner> toolResults) {
    this.toolResults = toolResults;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StepDetail stepDetail = (StepDetail) o;
    return Objects.equals(this.text, stepDetail.text) &&
        Objects.equals(this.toolCalls, stepDetail.toolCalls) &&
        Objects.equals(this.toolResults, stepDetail.toolResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, toolCalls, toolResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StepDetail {\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    toolCalls: ").append(toIndentedString(toolCalls)).append("\n");
    sb.append("    toolResults: ").append(toIndentedString(toolResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("text", "toolCalls", "toolResults"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StepDetail
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StepDetail.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in StepDetail is not found in the empty JSON string", StepDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StepDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StepDetail` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
      if (jsonObj.get("toolCalls") != null && !jsonObj.get("toolCalls").isJsonNull()) {
        JsonArray jsonArraytoolCalls = jsonObj.getAsJsonArray("toolCalls");
        if (jsonArraytoolCalls != null) {
          // ensure the json data is an array
          if (!jsonObj.get("toolCalls").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `toolCalls` to be an array in the JSON string but got `%s`", jsonObj.get("toolCalls").toString()));
          }

          // validate the optional field `toolCalls` (array)
          for (int i = 0; i < jsonArraytoolCalls.size(); i++) {
            StepDetailToolCallsInner.validateJsonElement(jsonArraytoolCalls.get(i));
          };
        }
      }
      if (jsonObj.get("toolResults") != null && !jsonObj.get("toolResults").isJsonNull()) {
        JsonArray jsonArraytoolResults = jsonObj.getAsJsonArray("toolResults");
        if (jsonArraytoolResults != null) {
          // ensure the json data is an array
          if (!jsonObj.get("toolResults").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `toolResults` to be an array in the JSON string but got `%s`", jsonObj.get("toolResults").toString()));
          }

          // validate the optional field `toolResults` (array)
          for (int i = 0; i < jsonArraytoolResults.size(); i++) {
            StepDetailToolResultsInner.validateJsonElement(jsonArraytoolResults.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StepDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StepDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StepDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StepDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<StepDetail>() {
           @Override
           public void write(JsonWriter out, StepDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StepDetail read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StepDetail given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StepDetail
   * @throws IOException if the JSON string is invalid with respect to StepDetail
   */
  public static StepDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StepDetail.class);
  }

  /**
   * Convert an instance of StepDetail to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

