/*
 * Firecrawl Agent API
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.firecrawl.agent.model;

import java.util.Objects;
import com.firecrawl.agent.model.ModelConfig;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.firecrawl.agent.JSON;

/**
 * SubAgentConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-06T10:50:08.867642-04:00[America/Toronto]", comments = "Generator version: 7.21.0")
public class SubAgentConfig {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nonnull
  private String description;

  public static final String SERIALIZED_NAME_INSTRUCTIONS = "instructions";
  @SerializedName(SERIALIZED_NAME_INSTRUCTIONS)
  @javax.annotation.Nullable
  private String instructions;

  public static final String SERIALIZED_NAME_MODEL = "model";
  @SerializedName(SERIALIZED_NAME_MODEL)
  @javax.annotation.Nullable
  private ModelConfig model;

  /**
   * Gets or Sets tools
   */
  @JsonAdapter(ToolsEnum.Adapter.class)
  public enum ToolsEnum {
    SEARCH("search"),
    
    SCRAPE("scrape"),
    
    INTERACT("interact"),
    
    MAP("map");

    private String value;

    ToolsEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ToolsEnum fromValue(String value) {
      for (ToolsEnum b : ToolsEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ToolsEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ToolsEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ToolsEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ToolsEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ToolsEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TOOLS = "tools";
  @SerializedName(SERIALIZED_NAME_TOOLS)
  @javax.annotation.Nullable
  private List<ToolsEnum> tools = new ArrayList<>();

  public static final String SERIALIZED_NAME_SKILLS = "skills";
  @SerializedName(SERIALIZED_NAME_SKILLS)
  @javax.annotation.Nullable
  private List<String> skills = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAX_STEPS = "maxSteps";
  @SerializedName(SERIALIZED_NAME_MAX_STEPS)
  @javax.annotation.Nullable
  private Integer maxSteps = 10;

  public SubAgentConfig() {
  }

  public SubAgentConfig id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for this sub-agent (used as the tool name suffix).
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public SubAgentConfig name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Human-readable name shown in the tool description.
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public SubAgentConfig description(@javax.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * What this sub-agent does. Included in the tool description for the orchestrator.
   * @return description
   */
  @javax.annotation.Nonnull
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nonnull String description) {
    this.description = description;
  }


  public SubAgentConfig instructions(@javax.annotation.Nullable String instructions) {
    this.instructions = instructions;
    return this;
  }

  /**
   * Custom instructions appended to the sub-agent&#39;s system prompt.
   * @return instructions
   */
  @javax.annotation.Nullable
  public String getInstructions() {
    return instructions;
  }

  public void setInstructions(@javax.annotation.Nullable String instructions) {
    this.instructions = instructions;
  }


  public SubAgentConfig model(@javax.annotation.Nullable ModelConfig model) {
    this.model = model;
    return this;
  }

  /**
   * Get model
   * @return model
   */
  @javax.annotation.Nullable
  public ModelConfig getModel() {
    return model;
  }

  public void setModel(@javax.annotation.Nullable ModelConfig model) {
    this.model = model;
  }


  public SubAgentConfig tools(@javax.annotation.Nullable List<ToolsEnum> tools) {
    this.tools = tools;
    return this;
  }

  public SubAgentConfig addToolsItem(ToolsEnum toolsItem) {
    if (this.tools == null) {
      this.tools = new ArrayList<>();
    }
    this.tools.add(toolsItem);
    return this;
  }

  /**
   * Firecrawl tools available to this sub-agent.
   * @return tools
   */
  @javax.annotation.Nullable
  public List<ToolsEnum> getTools() {
    return tools;
  }

  public void setTools(@javax.annotation.Nullable List<ToolsEnum> tools) {
    this.tools = tools;
  }


  public SubAgentConfig skills(@javax.annotation.Nullable List<String> skills) {
    this.skills = skills;
    return this;
  }

  public SubAgentConfig addSkillsItem(String skillsItem) {
    if (this.skills == null) {
      this.skills = new ArrayList<>();
    }
    this.skills.add(skillsItem);
    return this;
  }

  /**
   * Skills to pre-load for this sub-agent.
   * @return skills
   */
  @javax.annotation.Nullable
  public List<String> getSkills() {
    return skills;
  }

  public void setSkills(@javax.annotation.Nullable List<String> skills) {
    this.skills = skills;
  }


  public SubAgentConfig maxSteps(@javax.annotation.Nullable Integer maxSteps) {
    this.maxSteps = maxSteps;
    return this;
  }

  /**
   * Maximum steps before the sub-agent stops.
   * minimum: 1
   * maximum: 50
   * @return maxSteps
   */
  @javax.annotation.Nullable
  public Integer getMaxSteps() {
    return maxSteps;
  }

  public void setMaxSteps(@javax.annotation.Nullable Integer maxSteps) {
    this.maxSteps = maxSteps;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubAgentConfig subAgentConfig = (SubAgentConfig) o;
    return Objects.equals(this.id, subAgentConfig.id) &&
        Objects.equals(this.name, subAgentConfig.name) &&
        Objects.equals(this.description, subAgentConfig.description) &&
        Objects.equals(this.instructions, subAgentConfig.instructions) &&
        Objects.equals(this.model, subAgentConfig.model) &&
        Objects.equals(this.tools, subAgentConfig.tools) &&
        Objects.equals(this.skills, subAgentConfig.skills) &&
        Objects.equals(this.maxSteps, subAgentConfig.maxSteps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, instructions, model, tools, skills, maxSteps);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubAgentConfig {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    instructions: ").append(toIndentedString(instructions)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("    skills: ").append(toIndentedString(skills)).append("\n");
    sb.append("    maxSteps: ").append(toIndentedString(maxSteps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("id", "name", "description", "instructions", "model", "tools", "skills", "maxSteps"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("id", "name", "description"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubAgentConfig
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubAgentConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SubAgentConfig is not found in the empty JSON string", SubAgentConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubAgentConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SubAgentConfig` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubAgentConfig.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("instructions") != null && !jsonObj.get("instructions").isJsonNull()) && !jsonObj.get("instructions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `instructions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("instructions").toString()));
      }
      // validate the optional field `model`
      if (jsonObj.get("model") != null && !jsonObj.get("model").isJsonNull()) {
        ModelConfig.validateJsonElement(jsonObj.get("model"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tools") != null && !jsonObj.get("tools").isJsonNull() && !jsonObj.get("tools").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tools` to be an array in the JSON string but got `%s`", jsonObj.get("tools").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("skills") != null && !jsonObj.get("skills").isJsonNull() && !jsonObj.get("skills").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `skills` to be an array in the JSON string but got `%s`", jsonObj.get("skills").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubAgentConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubAgentConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubAgentConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubAgentConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<SubAgentConfig>() {
           @Override
           public void write(JsonWriter out, SubAgentConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubAgentConfig read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubAgentConfig given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubAgentConfig
   * @throws IOException if the JSON string is invalid with respect to SubAgentConfig
   */
  public static SubAgentConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubAgentConfig.class);
  }

  /**
   * Convert an instance of SubAgentConfig to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

