/*
 * Firecrawl Agent API
 *
 * AI-powered web research agent built on Firecrawl. Search, scrape, and extract structured data from the web. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkerProgressStepLogInner {
    #[serde(rename = "tool", skip_serializing_if = "Option::is_none")]
    pub tool: Option<String>,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

impl WorkerProgressStepLogInner {
    pub fn new() -> WorkerProgressStepLogInner {
        WorkerProgressStepLogInner {
            tool: None,
            detail: None,
        }
    }
}

