//
// AgentEventOneOf3.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AgentEventOneOf3: Sendable, Codable, Hashable {

    public var type: JSONValue?
    public var usage: Usage?

    public init(type: JSONValue? = nil, usage: Usage? = nil) {
        self.type = type
        self.usage = usage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case usage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(usage, forKey: .usage)
    }
}

