//
// AgentEventOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AgentEventOneOf1: Sendable, Codable, Hashable {

    public var type: JSONValue?
    public var name: String?
    public var input: JSONValue?

    public init(type: JSONValue? = nil, name: String? = nil, input: JSONValue? = nil) {
        self.type = type
        self.name = name
        self.input = input
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case name
        case input
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(input, forKey: .input)
    }
}

