//
// RunRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RunRequest: Sendable, Codable, Hashable {

    public enum Format: String, Sendable, Codable, CaseIterable {
        case json = "json"
        case csv = "csv"
        case markdown = "markdown"
    }
    public static let maxStepsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 50, exclusiveMaximum: false, multipleOf: nil)
    /** The research task or question. */
    public var prompt: String
    /** If true, response is an SSE stream of AgentEvent objects. */
    public var stream: Bool? = false
    /** Desired output format. If set, agent will format data accordingly. */
    public var format: Format?
    /** JSON schema that serves as both a research plan and output format. The agent treats each field as a data point to collect during research. Array fields mean \"find all items.\" The final output is compiled into this exact shape. Used with format=json.  */
    public var schema: JSONValue?
    /** Column names for CSV output. Each column acts as a required data point the agent will research. The final CSV contains one column per entry.  */
    public var columns: [String]?
    /** Seed URLs to start from instead of searching. */
    public var urls: [String]?
    public var model: ModelConfig?
    public var subAgentModel: ModelConfig?
    /** Maximum agent steps before stopping. */
    public var maxSteps: Int? = 15
    /** Skills to pre-load for this run. */
    public var skills: [String]?
    /** Per-skill custom instructions. Keys are skill names, values are instruction strings appended when the skill is loaded.  */
    public var skillInstructions: [String: String]?
    /** Sub-agents available during this run. Each sub-agent becomes a tool the orchestrator can delegate tasks to.  */
    public var subAgents: [SubAgentConfig]?
    /** When true, post-processes the run into a reusable skill package (SKILL.md + workflow.mjs + schema.json) returned in the response.  */
    public var exportSkill: Bool? = false

    public init(prompt: String, stream: Bool? = false, format: Format? = nil, schema: JSONValue? = nil, columns: [String]? = nil, urls: [String]? = nil, model: ModelConfig? = nil, subAgentModel: ModelConfig? = nil, maxSteps: Int? = 15, skills: [String]? = nil, skillInstructions: [String: String]? = nil, subAgents: [SubAgentConfig]? = nil, exportSkill: Bool? = false) {
        self.prompt = prompt
        self.stream = stream
        self.format = format
        self.schema = schema
        self.columns = columns
        self.urls = urls
        self.model = model
        self.subAgentModel = subAgentModel
        self.maxSteps = maxSteps
        self.skills = skills
        self.skillInstructions = skillInstructions
        self.subAgents = subAgents
        self.exportSkill = exportSkill
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case prompt
        case stream
        case format
        case schema
        case columns
        case urls
        case model
        case subAgentModel
        case maxSteps
        case skills
        case skillInstructions
        case subAgents
        case exportSkill
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(prompt, forKey: .prompt)
        try container.encodeIfPresent(stream, forKey: .stream)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(schema, forKey: .schema)
        try container.encodeIfPresent(columns, forKey: .columns)
        try container.encodeIfPresent(urls, forKey: .urls)
        try container.encodeIfPresent(model, forKey: .model)
        try container.encodeIfPresent(subAgentModel, forKey: .subAgentModel)
        try container.encodeIfPresent(maxSteps, forKey: .maxSteps)
        try container.encodeIfPresent(skills, forKey: .skills)
        try container.encodeIfPresent(skillInstructions, forKey: .skillInstructions)
        try container.encodeIfPresent(subAgents, forKey: .subAgents)
        try container.encodeIfPresent(exportSkill, forKey: .exportSkill)
    }
}

